### ISSUE TITLE
IndexError: pop from empty list(Error with Keras-Tuner Args)

### ISSUE THREAD

**Issue by GuileCyclone** [keras-team/autokeras#1101]
### Bug Description
  When I try the newest feature(commit 68a2522 , add kt support (#1093) ) of master,I use distribution_strategy argument for trying to distribute tuning on multi-gpu.Code is here:

> kwargs = {'distribution_strategy': tf.distribute.MirroredStrategy()}
input_node = ak.ImageInput()
output_node = ak.ImageBlock(block_type='xception', normalize=True,augment=False)(input_node)
output_node = ak.ClassificationHead()(output_node)
clf = ak.AutoModel(inputs=input_node, outputs=output_node, max_trials=50, tuner='greedy' , overwrite=True, **kwargs)
clf.fit(x_train, y_train, epochs=10)

It pops error like this:

> Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\autokeras_test\lib\site-packages\kerastuner\engine\hypermodel.py", line 105, in build
    model = self.hypermodel.build(hp)
  File "C:\ProgramData\Anaconda3\envs\autokeras_test\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\ProgramData\Anaconda3\envs\autokeras_test\lib\site-packages\kerastuner\engine\hypermodel.py", line 170, in maybe_distribute
    yield
  File "C:\ProgramData\Anaconda3\envs\autokeras_test\lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 332, in __exit__
    _pop_per_thread_mode()
  File "C:\ProgramData\Anaconda3\envs\autokeras_test\lib\site-packages\tensorflow\python\distribute\distribution_strategy_context.py", line 65, in _pop_per_thread_mode
    ops.get_default_graph()._distribution_strategy_stack.pop(-1)  # pylint: disable=protected-access
IndexError: pop from empty list
[Warning] Invalid model 0/5
...
[Warning] Invalid model 4/5
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\autokeras_test\lib\site-packages\kerastuner\engine\hypermodel.py", line 105, in build
    model = self.hypermodel.build(hp)
  File "C:\ProgramData\Anaconda3\envs\autokeras_test\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\ProgramData\Anaconda3\envs\autokeras_test\lib\site-packages\kerastuner\engine\hypermodel.py", line 170, in maybe_distribute
    yield
  File "C:\ProgramData\Anaconda3\envs\autokeras_test\lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 332, in __exit__
    _pop_per_thread_mode()
  File "C:\ProgramData\Anaconda3\envs\autokeras_test\lib\site-packages\tensorflow\python\distribute\distribution_strategy_context.py", line 65, in _pop_per_thread_mode
    ops.get_default_graph()._distribution_strategy_stack.pop(-1)  # pylint: disable=protected-access
IndexError: pop from empty list
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\autokeras_test\lib\site-packages\kerastuner\engine\hypermodel.py", line 105, in build
    model = self.hypermodel.build(hp)
  File "C:\ProgramData\Anaconda3\envs\autokeras_test\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\ProgramData\Anaconda3\envs\autokeras_test\lib\site-packages\kerastuner\engine\hypermodel.py", line 170, in maybe_distribute
    yield
  File "C:\ProgramData\Anaconda3\envs\autokeras_test\lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 332, in __exit__
    _pop_per_thread_mode()
  File "C:\ProgramData\Anaconda3\envs\autokeras_test\lib\site-packages\tensorflow\python\distribute\distribution_strategy_context.py", line 65, in _pop_per_thread_mode
    ops.get_default_graph()._distribution_strategy_stack.pop(-1)  # pylint: disable=protected-access
IndexError: pop from empty list

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Professional Edition with Anaconda plugin 2020.1\plugins\python\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Professional Edition with Anaconda plugin 2020.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "F:/Code/autokeras/test_matlab_new_gpuser.py", line 40, in <module>
    clf.fit(x_train, y_train, epochs=10)
  File "F:\Code\autokeras\autokeras\auto_model.py", line 251, in fit
    **kwargs)
  File "F:\Code\autokeras\autokeras\engine\tuner.py", line 102, in search
    super().search(epochs=epochs, callbacks=new_callbacks, **fit_kwargs)
  File "C:\ProgramData\Anaconda3\envs\autokeras_test\lib\site-packages\kerastuner\engine\base_tuner.py", line 130, in search
    self.run_trial(trial, *fit_args, **fit_kwargs)
  File "F:\Code\autokeras\autokeras\engine\tuner.py", line 63, in run_trial
    model = self.hypermodel.build(trial.hyperparameters)
  File "C:\ProgramData\Anaconda3\envs\autokeras_test\lib\site-packages\kerastuner\engine\hypermodel.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\autokeras_test\lib\site-packages\kerastuner\engine\hypermodel.py", line 115, in build
    'Too many failed attempts to build model.')
RuntimeError: Too many failed attempts to build model.
[Warning] Invalid model 5/5

    When the kwargs got removed,it can run successfully as usual.

### Expected Behavior

    If this problem can't be solved,can you product the ability to distribute tuning on multi-gpu?Thank you for your amazing effort on AutoNAS !

### Setup Details
Include the details about the versions of:
 - OS type and version:Microsoft Windows [版本 10.0.18363.778]
 - Python: 3.7
 - autokeras: master(1.0.3,until commit 41c99fb)
 - keras-tuner:1.0.1
 - scikit-learn:0.22.2.post1
 - numpy:1.18.1
 - pandas:1.0.3
 - tensorflow:2.2.0rc3

**Comment by lephuc2019** [comment]
I have the same issue. @GuileCyclone did you find a solution?

**Comment by haifeng-jin** [comment]
This should be resolved in the latest release of AutoKeras 1.0.8. Are you using this one? Would you share the code and the full error message with us? Thanks. @lephuc2019
