### ISSUE TITLE
I have a problem with usage of multi-gpu

### ISSUE THREAD

**Issue by hyeonnnn** [keras-team/autokeras#1159]
Hi I cannot use multi-gpu with below error message.

```
Traceback (most recent call last):
  File "/userhome/user/autokeras/test.py", line 66, in <module>
    model = multi_gpu_model(model, gpus=2)
  File "/userhome/user/anaconda3/envs/autokeras/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/userhome/user/anaconda3/envs/autokeras/lib/python3.7/site-packages/tensorflow/python/keras/utils/multi_gpu_utils.py", line 225, in multi_gpu_model
    input_shape = tuple(x.shape.as_list())[1:]
AttributeError: 'NoneType' object has no attribute 'as_list'
```

Here is my code.

```
input_node = ak.ImageInput()
output_node = ak.ImageBlock()(input_node)
output_node = ak.ClassificationHead()(output_node)

model = ak.AutoModel(inputs=input_node, outputs=output_node, max_trials=50, name='hmi_512')

model.fit(train_input_data, train_target_data, epochs=100, validation_split=0.2, batch_size=1, shuffle=True, verbose=2)

```

tf-gpu version : 2.1.0
ak version : 1.0.2
python : 3.7.7
keras : 2.3.1

Do anyone have an idea about it?

Thank you

**Comment by haifeng-jin** [comment]
I believe we have fixed this in the latest version 1.0.3. Please let me know if it still doesn't work.
