### ISSUE TITLE
No longer able to load a model

### ISSUE THREAD

**Issue by sword134** [keras-team/autokeras#1232]
### Bug Description
I making a 4 layered LSTM and saving it with the below mentioned code. Whenever I try to load it again it throws me the following error: ValueError: Input 0 is incompatible with layer lstm: expected shape=(None, None, 143), found shape=[None, 150, 147]

### Bug Reproduction
Code for reproducing the bug:

```
# Split into training and testing
train_dataset, test_dataset = train_test_split(
    dataset, test_size=0.05, shuffle=False)

print(train_dataset)
print(test_dataset)

train_labels = train_dataset.pop(RESPONSEVARIABLE)
test_labels = test_dataset.pop(RESPONSEVARIABLE)

train_dataset = train_dataset.values.astype("float32")
test_dataset = test_dataset.values.astype("float32")

print("Original training data shape:")
print(train_dataset.shape)

y_train = train_labels[look_back:]  # (train_size-look_back,)
y_test = test_labels[look_back:]  # ((n_sample-train_size),)
print("Y training and test shape:")
print(y_train.shape, y_test.shape)
train_X = view_as_windows(train_dataset, (look_back, train_dataset.shape[1]))[
    :-1, 0]  # (train_size-look_back, look_back, n_features)
test_X = view_as_windows(test_dataset, (look_back, test_dataset.shape[1]))[
    :-1, 0]  # ((n_sample-train_size)-look_back, look_back, n_features)
print("X training and test shape:")
print(train_X.shape, test_X.shape)

input_node = ak.Input()
    output_node1 = ak.RNNBlock(return_sequences=True,
                               layer_type='lstm')(input_node)
    output_node2 = ak.RNNBlock(return_sequences=True,
                               layer_type='lstm')(output_node1)
    output_node3 = ak.RNNBlock(return_sequences=True,
                               layer_type='lstm')(output_node2)
    output_node4 = ak.RNNBlock(layer_type='lstm')(output_node3)
    output_node5 = ak.DenseBlock()(output_node4)
    output_node = ak.Merge()(
        [output_node1, output_node2, output_node3, output_node4, output_node5])
    output_nodefinal = ak.ClassificationHead()(output_node)

      my_callbacks = [tf.keras.callbacks.EarlyStopping(patience=15, restore_best_weights=True, monitor="accuracy", mode="auto"),      
tf.keras.callbacks.ModelCheckpoint(filepath="D:\AutoKerasProject\TimeseriesCallbackModel\TimeseriesCallbackModel", save_weights_only=True, monitor="val_accuracy", mode="auto", save_best_only=True)]

classifier = ak.AutoModel(
        inputs=input_node, outputs=output_nodefinal, max_trials=1, directory="D:\AutoKerasProject\TimeseriesModel", overwrite=True)

    classifier.fit(x=train_X, y=y_train, callbacks=my_callbacks)
    print("Done fitting, beginning evaluation:")
    print(classifier.evaluate(x=test_X, y=y_test))

    model = classifier.tuner.get_best_model()
    print(model.summary())
    model.save("D:\AutoKerasProject\hebestModel.h5")
```

The code I use to load the model with again:

```
modelLoaded = tf.keras.models.load_model('D:\AutoKerasProject\hebestModel.h5')
print(modelLoaded.summary())
y_prediction1 = modelLoaded.predict(train_X)
y_prediction = np.where(y_prediction1 < 0.5, "Up", "Down")
print(y_prediction)

scoredataset = pd.DataFrame(data=y_prediction)

```
The error I get:

```
WARNING:tensorflow:Model was constructed with shape (None, 150, 143) for input Tensor("input_1:0", shape=(None, 150, 143), dtype=float32), but it was called on an input with incompatible shape (None, 150, 147).
Traceback (most recent call last):
  File "d:\AutoKerasProject\AutoKeras. Load Model.py", line 94, in <module>
    y_prediction1 = modelLoaded.predict(train_X)
  File "D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\keras\engine\training.py", line 88, in _method_wrapper
    return method(self, *args, **kwargs)
  File "D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1268, in predict
    tmp_batch_outputs = predict_function(iterator)
  File "D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\eager\def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\eager\def_function.py", line 627, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\eager\def_function.py", line 506, in _initialize
    *args, **kwds))
  File "D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\eager\function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\eager\function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\eager\function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\framework\func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\eager\def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\framework\func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\keras\engine\training.py:1147 predict_function  *
        outputs = self.distribute_strategy.run(
    D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\keras\engine\training.py:1122 predict_step  **
        return self(x, training=False)
    D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:927 __call__
        outputs = call_fn(cast_inputs, *args, **kwargs)
    D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\keras\engine\network.py:719 call
        convert_kwargs_to_constants=base_layer_utils.call_context().saving)
    D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\keras\engine\network.py:888 _run_internal_graph
        output_tensors = layer(computed_tensors, **kwargs)
    D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\keras\layers\recurrent.py:654 __call__
        return super(RNN, self).__call__(inputs, **kwargs)
    D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:886 __call__
        self.name)
    D:\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:227 assert_input_compatibility
        ', found shape=' + str(shape))

    ValueError: Input 0 is incompatible with layer lstm: expected shape=(None, None, 143), found shape=[None, 150, 147]

```

### Expected Behavior
It should load the model and recreate the original results.

### Setup Details
Include the details about the versions of:
-OS type and version:
-Python: 3.6.10
-autokeras: 1.0.3
-keras-tuner: latest
-scikit-learn: 0.23.1
-numpy: 1.18.5
-pandas: 1.0.5
-tensorflow: 2.2.0

**Comment by haifeng-jin** [comment]
It seems it is caused by an incompatible input shape.
You may need to preprocess the input data a little bit to match the shape.
To ensure you preprocess the data properly,
you can always try to convert it to a tf.data.Dataset and see its shape.
```
ak.utils.data_utils.dataset_shape(dataset)
```

**Comment by sword134** [comment]
I preprocess my input data with the exact same (copy paste) code as in my model calculation. I even included it in the ticket above. It used to work a few weeks ago but for some reason it has stopped working, even though I haven't touched the code.
