### ISSUE TITLE
 LookupError: gradient registry has no entry for: AdjustContrastv2

### ISSUE THREAD

**Issue by koh-joshua** [keras-team/autokeras#1368]
### Bug Description
I am using AutoModel for image classification on multispectral images (25 x 25 x 10).
input_node = ak.Input(shape=(25, 25, 10))
output_node = ak.ConvBlock()(input_node)
output_node = ak.ImageBlock()(output_node)
output_node = ak.ClassificationHead()(output_node)
auto_model = ak.AutoModel(input_node,
                          output_node,
                          overwrite=True,
                          max_trials=50)
auto_model.fit(Xtrain, ytrain)

Everything runs fine until trial #17:
Traceback (most recent call last):
  File "<input>", line 26, in <module>
  File "C:\Anaconda3\envs\TSCNN\lib\site-packages\autokeras\auto_model.py", line 275, in fit
    **kwargs
  File "C:\Anaconda3\envs\TSCNN\lib\site-packages\autokeras\engine\tuner.py", line 173, in search
    super().search(epochs=epochs, callbacks=new_callbacks, **fit_kwargs)
  File "C:\Anaconda3\envs\TSCNN\lib\site-packages\kerastuner\engine\base_tuner.py", line 131, in search
    self.run_trial(trial, *fit_args, **fit_kwargs)
  File "C:\Anaconda3\envs\TSCNN\lib\site-packages\kerastuner\engine\tuner.py", line 155, in run_trial
    model.fit(*fit_args, **copied_fit_kwargs)
  File "C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\eager\def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\eager\def_function.py", line 697, in _initialize
    *args, **kwds))
  File "C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\eager\function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\eager\function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\eager\function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\framework\func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\eager\def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\framework\func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.autograph.impl.api.StagingError: in user code:
    C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\keras\engine\training.py:806 train_function  *
        return step_function(self, iterator)
    C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\keras\engine\training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\keras\engine\training.py:789 run_step  **
        outputs = model.train_step(data)
    C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\keras\engine\training.py:757 train_step
        self.trainable_variables)
    C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\keras\engine\training.py:2722 _minimize
        gradients = tape.gradient(loss, trainable_variables)
    C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\eager\backprop.py:1073 gradient
        unconnected_gradients=unconnected_gradients)
    C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\eager\imperative_grad.py:77 imperative_grad
        compat.as_str(unconnected_gradients.value))
    C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\eager\backprop.py:151 _gradient_function
        grad_fn = ops._gradient_registry.lookup(op_name)  # pylint: disable=protected-access
    C:\Anaconda3\envs\TSCNN\lib\site-packages\tensorflow\python\framework\registry.py:97 lookup
        "%s registry has no entry for: %s" % (self._name, name))
    **LookupError: gradient registry has no entry for: AdjustContrastv2**

AutoKeras: 1.0.9
Keras-tuner: 1.0.2rc2
Tensorflow 2.3.1
Python 3.7

**Comment by koh-joshua** [comment]
Looks like some issue with the inputs. Setting (augment=False) solved problem.

**Comment by nitinkumartech** [comment]
@koh-joshua Do you have a final code example that worked for you when using autokeras for multispectral images? Would be great to hear about autokeras and multispectral images
