### ISSUE TITLE
Failed to remove a directory

### ISSUE THREAD

**Issue by shushan2017** [keras-team/autokeras#1380]
**I run the following code,** 
**************************************************

for n in np.arange(0, 1000):
   y=fun(...,n)
   clf = ak.StructuredDataClassifier(overwrite=True,max_trials=3)
   clf.fit(X_train, y, epochs=50,verbose=0)
  ybw=(clf.evaluate(X_val, y_val))

***************
**and occasionally an error occurs to terminate the run**
**********************************************************************
Traceback (most recent call last):

  File "<ipython-input-8-6017aca8f0ea>", line 44, in <module>
    clf.fit(X_train, y_train, epochs=50,verbose=0)

  File "C:\ProgramData\Anaconda3\lib\site-packages\autokeras\tasks\structured_data.py", line 317, in fit
    **kwargs

  File "C:\ProgramData\Anaconda3\lib\site-packages\autokeras\tasks\structured_data.py", line 139, in fit
    **kwargs

  File "C:\ProgramData\Anaconda3\lib\site-packages\autokeras\auto_model.py", line 275, in fit
    **kwargs

  File "C:\ProgramData\Anaconda3\lib\site-packages\autokeras\engine\tuner.py", line 173, in search
    super().search(epochs=epochs, callbacks=new_callbacks, **fit_kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\kerastuner\engine\base_tuner.py", line 131, in search
    self.run_trial(trial, *fit_args, **fit_kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\kerastuner\engine\tuner.py", line 155, in run_trial
    model.fit(*fit_args, **copied_fit_kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1137, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\callbacks.py", line 416, in on_epoch_end
    callback.on_epoch_end(epoch, numpy_logs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\kerastuner\engine\tuner_utils.py", line 93, in on_epoch_end
    self.trial, self.model, epoch, logs=logs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\kerastuner\engine\tuner.py", line 242, in on_epoch_end
    self.save_model(trial.trial_id, model, step=epoch)

  File "C:\ProgramData\Anaconda3\lib\site-packages\kerastuner\engine\tuner.py", line 184, in save_model
    trial_id, epoch_to_delete)

  File "C:\ProgramData\Anaconda3\lib\site-packages\kerastuner\engine\tuner.py", line 316, in _delete_checkpoint
    tf.io.gfile.rmtree(self._get_checkpoint_dir(trial_id, epoch))

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 599, in delete_recursively_v2
    _pywrap_file_io.DeleteRecursively(compat.as_bytes(path))

FailedPreconditionError: Failed to remove a directory: .\structured_data_classifier\trial_b9de8038f6e5979597b81f038a11ea7e\checkpoints\epoch_23; Directory not empty

**Comment by haifeng-jin** [comment]
I am not sure why it cannot remove the dir.
Keras Tuner would always remove some dir to save disk space during the search.
It runs fine in my computer.

**Comment by LukasWohlfart** [comment]
same error for me. It is quite weird as it is not always after X-epochs... sometimes the first sometimes after 30.

really looking forward to a fix if anybody has a solution

**Comment by minhng22** [comment]
Is there any update on this issue? I am noticing same issue running on Windows

**Comment by ruwanifdo** [comment]
I am facing the same issue with `overwrite=True`. Is there a solution to this issue?
