### ISSUE TITLE
Having issue in converting autokeras functional model to onnx?

### ISSUE THREAD

**Issue by hanzigs** [keras-team/autokeras#1446]
Hi,
I am trying to convert autokeras model to onnx, i get error
```
from autokeras import StructuredDataClassifier
model = StructuredDataClassifier(max_trials=100)
model.fit(x=X_train, y=y_train, validation_data=(X_valid, y_valid), epochs=1000, verbose=1)
autoKeras_model = model.export_model()
autoKeras_model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 18)]              0         
_________________________________________________________________
multi_category_encoding (Mul (None, 18)                0         
_________________________________________________________________
dense (Dense)                (None, 32)                608       
_________________________________________________________________
re_lu (ReLU)                 (None, 32)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 32)                1056      
_________________________________________________________________
re_lu_1 (ReLU)               (None, 32)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 33        
_________________________________________________________________
classification_head_2 (Activ (None, 1)                 0         
=================================================================
Total params: 1,697
Trainable params: 1,697
Non-trainable params: 0
_________________________________________________________________
```
converting to onnx
```
import onnxruntime
import keras2onnx
onnx_model = keras2onnx.convert_keras(autoKeras_model, "autokeras", debug_mode=1)
```
I get error
```
tf executing eager_mode: True
INFO:keras2onnx:tf executing eager_mode: True
tf.keras model eager_mode: False
INFO:keras2onnx:tf.keras model eager_mode: False
Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 18)]              0         
_________________________________________________________________
multi_category_encoding (Mul (None, 18)                0         
_________________________________________________________________
dense (Dense)                (None, 32)                608       
_________________________________________________________________
re_lu (ReLU)                 (None, 32)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 32)                1056      
_________________________________________________________________
re_lu_1 (ReLU)               (None, 32)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 33        
_________________________________________________________________
classification_head_2 (Activ (None, 1)                 0         
=================================================================
Total params: 1,697
Trainable params: 1,697
Non-trainable params: 0
_________________________________________________________________
None
Traceback (most recent call last):

  File "<ipython-input-76-0567e6de6858>", line 1, in <module>
    onnx_model = keras2onnx.convert_keras(ExportedautoKeras_model, model_name, debug_mode=1)

  File "C:\Users\Pe\Anaconda3\lib\site-packages\keras2onnx\main.py", line 62, in convert_keras
    tf_graph = build_layer_output_from_model(model, output_dict, input_names, output_names)

  File "C:\Users\Pe\Anaconda3\lib\site-packages\keras2onnx\_parser_tf.py", line 302, in build_layer_output_from_model
    return extract_outputs_from_subclassing_model(model, output_dict, input_names, output_names)

  File "C:\Users\Pe\Anaconda3\lib\site-packages\keras2onnx\_parser_tf.py", line 264, in extract_outputs_from_subclassing_model
    concrete_func, lower_control_flow=True)

  File "C:\Users\Pe\Anaconda3\lib\site-packages\keras2onnx\_graph_cvt.py", line 437, in convert_variables_to_constants_v2
    tensor_data = _get_tensor_data(func)

  File "C:\Users\Pe\Anaconda3\lib\site-packages\keras2onnx\_graph_cvt.py", line 209, in _get_tensor_data
    data = val_tensor.numpy()

  File "C:\Users\Pe\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1063, in numpy
    maybe_arr = self._numpy()  # pylint: disable=protected-access

  File "C:\Users\Pe\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1031, in _numpy
    six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access

  File "<string>", line 3, in raise_from

InvalidArgumentError: Cannot convert a Tensor of dtype resource to a NumPy array.
```
May i have some help
Thanks

**Comment by hanzigs** [comment]
Hi , Can I have some help on the above please, Thanks

**Comment by hanzigs** [comment]
Hi, Can you keep this open, I am still looking for some solution, Thanks

**Comment by haifeng-jin** [comment]
I am not familiar with ONNX.
However, AutoKeras is using some custom layers and extending the preprocessing layer class, which is a latest feature of Keras.
Therefore, I guess it is not supported in ONNX yet.

**Comment by hanzigs** [comment]
Hi,
This is not ONNX issue, this is issue in tensorflow, 
"Resource types are supported through only saved model converter since TF 2.5"

is there any option in autokeras exporting model to overcome this issue
Thanks

**Comment by hanzigs** [comment]
Tensorflow 2.5 in python 3.9.5 cleared this issue, it worked

**Comment by torronen** [comment]
I still have same issue on Tensorflow 2.5.2, Python 3.9.7

```
Traceback (most recent call last):
  File "Q:\autokeras\autokeras10.py", line 168, in <module>
    onnx_model = keras2onnx.convert_keras(model, model.name)
  File "C:\Users\inno1\.conda\envs\autokeras\lib\site-packages\keras2onnx\main.py", line 62, in convert_keras
    tf_graph = build_layer_output_from_model(model, output_dict, input_names, output_names)
  File "C:\Users\inno1\.conda\envs\autokeras\lib\site-packages\keras2onnx\_parser_tf.py", line 302, in build_layer_output_from_model
    return extract_outputs_from_subclassing_model(model, output_dict, input_names, output_names)
  File "C:\Users\inno1\.conda\envs\autokeras\lib\site-packages\keras2onnx\_parser_tf.py", line 263, in extract_outputs_from_subclassing_model
    graph_def, converted_input_indices = _convert_to_constants(
  File "C:\Users\inno1\.conda\envs\autokeras\lib\site-packages\keras2onnx\_graph_cvt.py", line 437, in convert_variables_to_constants_v2
    tensor_data = _get_tensor_data(func)
  File "C:\Users\inno1\.conda\envs\autokeras\lib\site-packages\keras2onnx\_graph_cvt.py", line 209, in _get_tensor_data
    data = val_tensor.numpy()
  File "C:\Users\inno1\.conda\envs\autokeras\lib\site-packages\tensorflow\python\framework\ops.py", line 1094, in numpy
    maybe_arr = self._numpy()  # pylint: disable=protected-access
  File "C:\Users\inno1\.conda\envs\autokeras\lib\site-packages\tensorflow\python\framework\ops.py", line 1062, in _numpy
    six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot convert a Tensor of dtype resource to a NumPy array.
```

**Comment by torronen** [comment]
Here is the model summary

```
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 2651)]            0
_________________________________________________________________
multi_category_encoding (Mul (None, 2651)              0
_________________________________________________________________
normalization (Normalization (None, 2651)              5303
_________________________________________________________________
dense (Dense)                (None, 32)                84864
_________________________________________________________________
re_lu (ReLU)                 (None, 32)                0
_________________________________________________________________
dense_1 (Dense)              (None, 32)                1056
_________________________________________________________________
re_lu_1 (ReLU)               (None, 32)                0
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 33
_________________________________________________________________
classification_head_1 (Activ (None, 1)                 0
=================================================================
Total params: 91,256
Trainable params: 85,953
Non-trainable params: 5,303
_________________________________________________________________
```

**Comment by torronen** [comment]
Might be due to old version of keras2onnx
```
pip install git+https://github.com/microsoft/onnxconverter-common
pip install git+https://github.com/onnx/keras-onnx
```

Can not confirm it yet, but just in case for others, in case I forget to come back.

**Comment by hanzigs** [comment]
@torronen 
Following combinations working fine for me
```
pip install tensorflow==2.5.0
pip install keras==2.4.3
pip install keras-tuner==1.0.3
pip install autokeras==1.0.16
pip install tf2onnx==1.9.2
pip install keras2onnx==1.7.0
pip install onnxruntime==1.8.0
pip install onnxmltools==1.7.0

model = StructuredDataClassifier(...........)
akmodel.fit(......)
onnx_model, _ = tf2onnx.convert.from_keras(model)
```

**Comment by torronen** [comment]
Thank you @hanzigs , that solved the issue. 

I believe my problem was using keras2onnx instead of tf2onnx. Package versioning may have had something to do with it, but probably not.

 onnx_model, _ = tf2onnx.convert.from_keras(model)
