### ISSUE TITLE
RuntimeError: Too many failed attempts to build model when running Multivariate Regression (StructuredDataRegressor)

### ISSUE THREAD

**Issue by mkressecondo** [keras-team/autokeras#1551]
### Bug Description
The following error is being raised when running multivariate regression. I noticed that the issue only occurs when running multivariate regression, not when running univariate regression. 

    Invalid model 5/5
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/kerastuner/engine/hypermodel.py", line 104, in build
        model = self.hypermodel.build(hp)
      File "/usr/local/lib/python3.9/site-packages/kerastuner/engine/hypermodel.py", line 64, in _build_wrapper
        return self._build(hp, *args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/autokeras/graph.py", line 250, in build
        outputs = block.build(hp, inputs=temp_inputs)
      File "/usr/local/lib/python3.9/site-packages/autokeras/engine/block.py", line 38, in _build_wrapper
        return super()._build_wrapper(hp, *args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/kerastuner/engine/hypermodel.py", line 64, in _build_wrapper
        return self._build(hp, *args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/autokeras/blocks/wrapper.py", line 249, in build
        output_node = block.build(hp, output_node)
      File "/usr/local/lib/python3.9/site-packages/autokeras/engine/block.py", line 38, in _build_wrapper
        return super()._build_wrapper(hp, *args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/kerastuner/engine/hypermodel.py", line 64, in _build_wrapper
        return self._build(hp, *args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/autokeras/blocks/preprocessing.py", line 280, in build
        return keras_layers.MultiCategoryEncoding(encoding)(input_node)
      File "/usr/local/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 969, in __call__
        return self._functional_construction_call(inputs, args, kwargs,
      File "/usr/local/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1107, in _functional_construction_call
        outputs = self._keras_tensor_symbolic_call(
      File "/usr/local/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 840, in _keras_tensor_symbolic_call
        return self._infer_output_signature(inputs, args, kwargs, input_masks)
      File "/usr/local/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 880, in _infer_output_signature
        outputs = call_fn(inputs, *args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 695, in wrapper
        raise e.ag_error_metadata.to_exception(e)
    ValueError: in user code:

        /usr/local/lib/python3.9/site-packages/autokeras/keras_layers.py:90 call  *
            output_nodes.append(
        /usr/local/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py:1030 __call__  **
            outputs = call_fn(inputs, *args, **kwargs)
        /usr/local/lib/python3.9/site-packages/tensorflow/python/keras/layers/preprocessing/index_lookup.py:600 call
            raise ValueError("You must set the layer's vocabulary before calling it. "

    ValueError: You must set the layer's vocabulary before calling it. Either pass a `vocabulary` argument to the layer, or call `layer.adapt(dataset)` with some sample data.

    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/marcelkresse/Desktop/autokeras_test.py", line 112, in <module>
        reg.fit(
      File "/usr/local/lib/python3.9/site-packages/autokeras/tasks/structured_data.py", line 134, in fit
        super().fit(
      File "/usr/local/lib/python3.9/site-packages/autokeras/auto_model.py", line 273, in fit
        self.tuner.search(
      File "/usr/local/lib/python3.9/site-packages/autokeras/engine/tuner.py", line 178, in search
        self.hypermodel.build(hp)
      File "/usr/local/lib/python3.9/site-packages/kerastuner/engine/hypermodel.py", line 64, in _build_wrapper
        return self._build(hp, *args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/kerastuner/engine/hypermodel.py", line 112, in build
        raise RuntimeError(
    RuntimeError: Too many failed attempts to build model.

### Bug Reproduction
Code for reproducing the bug:
The code is from the official ak documentation: https://autokeras.com/tutorial/structured_data_regression/

# 1. Code which causes error (Multivariate Regression):

import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.datasets import fetch_california_housing
import autokeras as ak

house_dataset = fetch_california_housing()
df = pd.DataFrame(
    np.concatenate(
        (house_dataset.data, house_dataset.target.reshape(-1, 1)), axis=1
    ),
    columns=house_dataset.feature_names + ["Price"],
)
train_size = int(df.shape[0] * 0.9)
df[:train_size].to_csv("train.csv", index=False)
df[train_size:].to_csv("eval.csv", index=False)
train_file_path = "train.csv"
test_file_path = "eval.csv"

### Initialize the structured data regressor.
reg = ak.StructuredDataRegressor(
    overwrite=True, max_trials=3
)  # It tries 3 different models.
### Feed the structured data regressor with training data.
reg.fit(
    # The path to the train.csv file.
    train_file_path,
    # The name of the label column.
    "Price",
    epochs=10,
)
### Predict with the best model.
predicted_y = reg.predict(test_file_path)
### Evaluate the best model with testing data.
print(reg.evaluate(test_file_path, "Price"))

# 2. Code which does not cause error (Univariate Regression):

import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.datasets import fetch_california_housing
import autokeras as ak

house_dataset = fetch_california_housing()

df = pd.DataFrame(
    np.concatenate(
        (house_dataset.data[:,0].reshape(-1, 1), house_dataset.target.reshape(-1, 1)), axis=1
    ),
    columns=[house_dataset.feature_names[0]] + ["Price"],
)
train_size = int(df.shape[0] * 0.9)
df[:train_size].to_csv("train.csv", index=False)
df[train_size:].to_csv("eval.csv", index=False)
train_file_path = "train.csv"
test_file_path = "eval.csv"

### Initialize the structured data regressor.
reg = ak.StructuredDataRegressor(
    overwrite=True, max_trials=3
)  # It tries 3 different models.
### Feed the structured data regressor with training data.
reg.fit(
    # The path to the train.csv file.
    train_file_path,
    # The name of the label column.
    "Price",
    epochs=10,
)
### Predict with the best model.
predicted_y = reg.predict(test_file_path)
### Evaluate the best model with testing data.
print(reg.evaluate(test_file_path, "Price"))

# Setup Details
Include the details about the versions of:
 - OS type and version: MacOS Catalina, version: 10.15.7
 - Python: 3.9.2
 - autokeras: 1.0.12
 - keras-tuner:1.0.2
 - scikit-learn:0.24.1
 - numpy:1.19.5
 - pandas:1.2.3
 - tensorflow:2.5.0-rc1

**Comment by Mathefreak007** [comment]
Same issue for me and no idea how to fix it. Error message dosn't give me a glue what to do.
Any ideas to solve that problem?
