### ISSUE TITLE
Custom mask layers require a config and must override get_config

### ISSUE THREAD

**Issue by tmtong** [keras-team/autokeras#1557]
### Bug Description

Custom mask layers require a config and must override get_config

### Bug Reproduction
```
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import mnist
import autokeras as ak

physical_devices = tf.config.experimental.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)


(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)  # (60000, 28, 28)
print(y_train.shape)  # (60000,)
print(y_train[:3])  # array([7, 2, 1], dtype=uint8)



reg = ak.ImageRegressor(max_trials=1)
# Feed the image regressor with training data.
reg.fit(x_train, y_train, epochs=2)


# Predict with the best model.
predicted_y = reg.predict(x_test)
print(predicted_y)
```

### Error produced
2021-05-08 16:57:37.822677: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
/home/tmtong/.local/lib/python3.9/site-packages/tensorflow/python/keras/utils/generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '
Traceback (most recent call last):
  File "/home/tmtong/Documents/autokeras-tutorial/image_classify.py", line 23, in <module>
    predicted_y = reg.predict(x_test)
  File "/home/tmtong/.local/lib/python3.9/site-packages/autokeras/auto_model.py", line 427, in predict
    model = self.tuner.get_best_model()
  File "/home/tmtong/.local/lib/python3.9/site-packages/autokeras/engine/tuner.py", line 63, in get_best_model
    model = tf.keras.models.load_model(self.best_model_path)
  File "/home/tmtong/.local/lib/python3.9/site-packages/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/home/tmtong/.local/lib/python3.9/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 155, in load
    keras_loader.finalize_objects()
  File "/home/tmtong/.local/lib/python3.9/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 626, in finalize_objects
    self._reconstruct_all_models()
  File "/home/tmtong/.local/lib/python3.9/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 645, in _reconstruct_all_models
    self._reconstruct_model(model_id, model, layers)
  File "/home/tmtong/.local/lib/python3.9/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 691, in _reconstruct_model
    created_layers) = functional_lib.reconstruct_from_config(
  File "/home/tmtong/.local/lib/python3.9/site-packages/tensorflow/python/keras/engine/functional.py", line 1289, in reconstruct_from_config
    process_node(layer, node_data)
  File "/home/tmtong/.local/lib/python3.9/site-packages/tensorflow/python/keras/engine/functional.py", line 1237, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "/home/tmtong/.local/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 969, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/home/tmtong/.local/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1107, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/home/tmtong/.local/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 840, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/tmtong/.local/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer.py", line 880, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/tmtong/.local/lib/python3.9/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 855, in _unable_to_call_layer_due_to_serialization_issue
    raise ValueError(
ValueError: Cannot call custom layer cast_to_float32 of type <class 'tensorflow.python.keras.saving.saved_model.load.Custom>CastToFloat32'>, because the call function was not serialized to the SavedModel.Please try one of the following methods to fix this issue:

(1) Implement `get_config` and `from_config` in the layer/model class, and pass the object to the `custom_objects` argument when loading the model. For more details, see: https://www.tensorflow.org/guide/keras/save_and_serialize

(2) Ensure that the subclassed model or layer overwrites `call` and not `__call__`. The input shape and dtype will be automatically recorded when the object is called, and used when saving. To manually specify the input shape/dtype, decorate the call function with `@tf.function(input_signature=...)`.

### Expected Behavior
Should run without problem 

### Setup Details
Include the details about the versions of:
 - OS type and version:
 - Python: 3.9.4
 - autokeras: 
 - keras-tuner:
 - scikit-learn:
 - numpy:
 - pandas:
 - tensorflow: 2.4.1

**Comment by tmtong** [comment]
I give up on this library. Too many bugs. If it works, it takes days, weeks and consume all the computer resources, including harddisk space.
