### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by talhaanwarch** [keras-team/autokeras#1583]
I am trying to load data from a dataframe

image | label
-- | --
train/class0/376.jpg | 0
train/class1/2.jpg | 1
train/class1/5/266.jpg | 1
train/class1/4.jpg | 1
train/class0/7.jpg | 0

```
def load(image_path,label):
  img = tf.io.read_file(image_path)
  img = tf.image.decode_jpeg(img, channels=1)
  img = tf.image.convert_image_dtype(img, tf.float32)
  label = tf.cast(label, tf.int32)
  return img, label

bs=10
train_ds = tf.data.Dataset.from_tensor_slices((train_df.image,train_df.label)).map(load).batch(bs)


import autokeras as ak
clf = ak.ImageClassifier(overwrite=True, max_trials=1)#also tried with False
clf.fit(train_ds, epochs=1)```
I have tried this
```
x=train_ds.take(1)
dataset_to_numpy = list(x.as_numpy_iterator())
print(dataset_to_numpy[0][0].shape,dataset_to_numpy[0][1].shape)
```
and got `(10, 224, 224, 1) (10,)`

I am getting the following error

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/kerastuner/engine/hypermodel.py", line 104, in build
    model = self.hypermodel.build(hp)
  File "/usr/local/lib/python3.7/dist-packages/kerastuner/engine/hypermodel.py", line 64, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/autokeras/graph.py", line 250, in build
    outputs = block.build(hp, inputs=temp_inputs)
  File "/usr/local/lib/python3.7/dist-packages/autokeras/engine/block.py", line 38, in _build_wrapper
    return super()._build_wrapper(hp, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kerastuner/engine/hypermodel.py", line 64, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/autokeras/blocks/wrapper.py", line 108, in build
    output_node = self._build_block(hp, output_node, block_type)
  File "/usr/local/lib/python3.7/dist-packages/autokeras/blocks/wrapper.py", line 77, in _build_block
    return basic.ResNetBlock().build(hp, output_node)
  File "/usr/local/lib/python3.7/dist-packages/autokeras/engine/block.py", line 38, in _build_wrapper
    return super()._build_wrapper(hp, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/kerastuner/engine/hypermodel.py", line 64, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/autokeras/blocks/basic.py", line 688, in build
    if input_node.shape[1] < min_size or input_node.shape[2] < min_size:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by holinov** [comment]
Same issue. Bump
