### ISSUE TITLE
[question] autokeras does not initialize: ModuleNotFoundError: No module named 'tensorflow.python.keras.preprocessing'

### ISSUE THREAD

**Issue by aanno** [keras-team/autokeras#1644]
Hello, 

I'm trying to run the jupyter examples from your great 'Automated Machine Learning in Action'. For this, I setup an conda env with your `requirements.txt`. I'm relative new to python dependencies and conda, and initializing autokeras does not work:

```python
>>> import autokeras as ak
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3-4.10.3/envs/automl38/lib/python3.8/site-packages/autokeras/__init__.py", line 15, in <module>
    from autokeras.auto_model import AutoModel
  File "/opt/miniconda3-4.10.3/envs/automl38/lib/python3.8/site-packages/autokeras/auto_model.py", line 26, in <module>
    from autokeras import graph as graph_module
  File "/opt/miniconda3-4.10.3/envs/automl38/lib/python3.8/site-packages/autokeras/graph.py", line 24, in <module>
    from autokeras.utils import io_utils
  File "/opt/miniconda3-4.10.3/envs/automl38/lib/python3.8/site-packages/autokeras/utils/io_utils.py", line 21, in <module>
    from tensorflow.python.keras.preprocessing import dataset_utils
ModuleNotFoundError: No module named 'tensorflow.python.keras.preprocessing'
```

In addition, I'm a bit confused with tf2 and keras and got the following questions:

* I'm using a self compiled version of tensorflow 2.8.0. Is keras already included?
* Does tensorflow still depend on the keras package? And if so, what keras version to install?
* I only see a `data_utils.py` in `keras_nightly` (2.8.0) (i.e. _not_ in `keras` (2.7.0)). Can I use `keras_nightly` instead of `keras` as a drop-in?
* There is also a `Keras-Preprocessing` (1.1.2) package? I'm I in need of it?

Kind regards,

aanno

**Comment by aanno** [comment]
I guess I could answer the question: _You have to stick to the version given in `requirement.txt`_ 

An easy try to reset the versions is:

```bash
pip install --force-reinstall autokeras==1.0.17rc1 keras-nightly==2.8.0.dev2021101807 keras-tuner==1.1.0rc0 tf-nightly==2.8.0.dev20211016
```

All these packages are _not_ available on `conda` (but you can still install the rest with is, e.g. `conda install jupyterlab`).
