### ISSUE TITLE
Initial network generation seems not try different architectures to fit max_model_size 

### ISSUE THREAD

**Issue by rzese** [keras-team/autokeras#1656]
### Bug Description
I need to impose a limit on the size of the network. However, if I set `max_model_size` I cannot start any training. The library creates 5 networks that are all equal (5 is the value set for `_max_fail_streak`). Thus, if the first network created is larger than the limit set with `max_model_size`, tries to create 5 equal networks, all out of limit, and stops returning the error `RuntimeError: Too many consecutive oversized models.`

### Bug Reproduction
```
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)  # (60000, 28, 28)
print(y_train.shape)  # (60000,)
print(y_train[:3])  # array([7, 2, 1], dtype=uint8)

input_node = ak.ImageInput()
output_node = ak.ImageBlock(
    block_type="vanilla",
    # Normalize the dataset.
    normalize=True,
    # Do not do data augmentation.
    augment=False,
)(input_node)
output_node = ak.ClassificationHead()(output_node)
clf = ak.AutoModel(
    inputs=input_node, outputs=output_node, overwrite=True, max_trials=1, max_model_size=10000,
    tuner="random"
)
clf.fit(x_train, y_train, epochs=10)
```

### Expected Behavior
```
Oversized model: 33194 parameters -- skipping
Oversized model: 33194 parameters -- skipping
Oversized model: 33194 parameters -- skipping
Oversized model: 33194 parameters -- skipping
Oversized model: 33194 parameters -- skipping
Oversized model: 33194 parameters -- skipping
Traceback (most recent call last):
  File "<path>/test_autokeras.py", line 31, in <module>
    clf.fit(x_train, y_train, epochs=10)
  File "<path>\autokeras_venv\lib\site-packages\autokeras\auto_model.py", line 284, in fit
    history = self.tuner.search(
  File "<path>\autokeras_venv\lib\site-packages\autokeras\engine\tuner.py", line 185, in search
    self.hypermodel.build(hp)
  File "<path>\autokeras_venv\lib\site-packages\keras_tuner\engine\hypermodel.py", line 84, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "<path>\autokeras_venv\lib\site-packages\keras_tuner\engine\hypermodel.py", line 150, in build
    raise RuntimeError("Too many consecutive oversized models.")
RuntimeError: Too many consecutive oversized models.

Process finished with exit code 1
```

### Setup Details
Include the details about the versions of:
 - OS type and version: Windows 10 64bit
 - Python: 3.8
 - autokeras: 1.0.16.post1
 - keras-tuner: 1.0.4
 - scikit-learn: 1.0.1
 - numpy: 1.19.5
 - pandas: 1.3.4
 - tensorflow: 2.5.2

**Comment by micheleFraccaroli** [comment]
I've found the same behaviour. 
The first created network is always the same.
Does someone have a solution?

**Comment by eschibli** [comment]
@rzese this is [issue 1479](https://github.com/keras-team/autokeras/issues/1479). It hasn't been solved yet and I'm not aware of a workaround unfortunately.

**Comment by rzese** [comment]
I saw that, thank you @eschibli. It is a pity because the library would benefit a lot from this fix in my opinion.

**Comment by ehavener** [comment]
This bug is present upstream in keras-tuner and there is a keras-tuner specific dirty fix described here [keras-tuner issue 175](https://github.com/keras-team/keras-tuner/issues/175#issuecomment-829440429). I wonder if we may adapt that fix to be compatible with autokeras? That might give us enough context to then implement the solution described [here in issue 1479](https://github.com/keras-team/autokeras/issues/1479#issuecomment-802279289)

**Comment by BenUCL** [comment]
I'm also getting this issue, using base colab versions other than reverting back to tf 2.8.3
