### ISSUE TITLE
Bug: 'Normalization' object has no attribute '_combiner' on macOS 

### ISSUE THREAD

**Issue by jakob-fankhauser** [keras-team/autokeras#1729]
### Bug Description
Trying to import autokeras leads to `AttributeError: 'Normalization' object has no attribute '_combiner'` in `autokeras/keras_layers.py:13`

### Bug Reproduction
import autokeras as ak

### Setup Details
Include the details about the versions of:
 - OS type and version: macOS Monterey 12.3.1
 - Python: 3.8
 - autokeras: 1.0.2
 - keras-tuner: 1.1.2
 - scikit-learn: 1.0.2
 - numpy: 1.21.4
 - pandas: 1.3.4
 - tensorflow-datasets: 4.5.2
 - tensorflow-macos: 2.8.0
- tensorflow-metadata: 1.7.0
- tensorflow-metal: 0.4.0

<img width="882" alt="Screenshot 2022-05-17 at 14 11 43" src="https://user-images.githubusercontent.com/77740361/168807923-c1a7ceb0-08a1-419c-943e-4f0454f2ccb7.png">

**Comment by MilesMartinez** [comment]
Encountered this same issue using tensorflow-metal on M1 Mac and this fixed it for me `pip install autokeras==1.0.19 --no-deps` works just fine now hope it helps

**Comment by haifeng-jin** [comment]
I do not have a mac to debug it right now.
Would someone please paste the full stacktrace?

Thanks.
It seems an important issue. No one can use AutoKeras on Mac.

**Comment by MilesMartinez** [comment]
Here is the full trace

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/milesmartinez/miniforge3/envs/lemon/lib/python3.10/site-packages/autokeras/__init__.py", line 1, in <module>
    from autokeras.auto_model import AutoModel
  File "/Users/milesmartinez/miniforge3/envs/lemon/lib/python3.10/site-packages/autokeras/auto_model.py", line 11, in <module>
    from autokeras import graph as graph_module
  File "/Users/milesmartinez/miniforge3/envs/lemon/lib/python3.10/site-packages/autokeras/graph.py", line 5, in <module>
    from autokeras import hypermodels
  File "/Users/milesmartinez/miniforge3/envs/lemon/lib/python3.10/site-packages/autokeras/hypermodels/__init__.py", line 7, in <module>
    from autokeras.hypermodels.heads import ClassificationHead
  File "/Users/milesmartinez/miniforge3/envs/lemon/lib/python3.10/site-packages/autokeras/hypermodels/heads.py", line 5, in <module>
    from autokeras import keras_layers
  File "/Users/milesmartinez/miniforge3/envs/lemon/lib/python3.10/site-packages/autokeras/keras_layers.py", line 11, in <module>
    Combiner = inspect.getmro(preprocessing.Normalization()._combiner.__class__)[1]
AttributeError: 'Normalization' object has no attribute '_combiner'
```
