### ISSUE TITLE
CuDNN error: CUDNN_STATUS_NOT_SUPPORTED.

### ISSUE THREAD

**Issue by hlalibe** [keras-team/autokeras#198]
Trying the sample code in the intro with 2523 images (533x533 pic) in training set and 100 in test set.

receive this error below on this line:
`clf.fit(x_train, y_train, time_limit=12 * 60 * 60)`

after Init search/init finished/training mode 0

```
~/anaconda3/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

RuntimeError: CuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
```
Running in Python 3 from Jupyter Notebook on Ubuntu 16.04 with Nvidia Titan XP
(Cuda installed and running with other DL programs)

**Comment by nivniv850** [comment]
I have the same issue, Anyone ?

**Comment by LuneZ99** [comment]
The same issue when I tried a (42839, 240, 240, 3) dataset.
I've trained for around 3 days and finally get this error when 'Training model 164'.
Running under Ubuntu 16.04 512 GB RAM, Nvidia RTX 2080Ti with CUDA10.0 and cuDNN 7.5.1.

> Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/search.py", line 363, in train
    raise e
  File "/usr/local/lib/python3.6/dist-packages/autokeras/search.py", line 356, in train
    verbose=verbose).train_model(**trainer_args)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/backend/torch/model_trainer.py", line 109, in train_model
    self._train()
  File "/usr/local/lib/python3.6/dist-packages/autokeras/backend/torch/model_trainer.py", line 145, in _train
    outputs = self.model(inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/backend/torch/model.py", line 51, in forward
    temp_tensor = torch_layer(edge_input_tensor)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
