### ISSUE TITLE
In case of  using TextClassifier, cannot export keras model

### ISSUE THREAD

**Issue by lhideki** [keras-team/autokeras#394]
### Bug Description

In case of  using TextClassifier, I export final fitted model as keras and it occurs the following exception.

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-27597b12761d> in <module>()
      3 
      4 model_filename = 'models/text_model.h5'
----> 5 classifier.export_keras_model(model_filename)

~\workspace\auto-keras\autokeras\autokeras\supervised.py in export_keras_model(self, model_file_name)
    183     def export_keras_model(self, model_file_name):
    184         """ Exports the best Keras model to the given filename. """
--> 185         self.cnn.best_model.produce_keras_model().save(model_file_name)
    186 
    187     def predict(self, x_test):

~\workspace\auto-keras\autokeras\autokeras\nn\graph.py in produce_keras_model(self)
    572     def produce_keras_model(self):
    573         """Build a new keras model based on the current graph."""
--> 574         return KerasModel(self).model
    575 
    576     def _layer_ids_in_order(self, layer_ids):

~\workspace\auto-keras\autokeras\autokeras\nn\graph.py in __init__(self, graph)
    724                     edge_input_tensor = node_list[u]
    725 
--> 726                 temp_tensor = keras_layer(edge_input_tensor)
    727                 node_list[v] = temp_tensor
    728 

~\AppData\Roaming\Python\Python36\site-packages\keras\engine\base_layer.py in __call__(self, inputs, **kwargs)
    412                 # Raise exceptions in case the input is not compatible
    413                 # with the input_spec specified in the layer constructor.
--> 414                 self.assert_input_compatibility(inputs)
    415 
    416                 # Collect input shapes to build layer.

~\AppData\Roaming\Python\Python36\site-packages\keras\engine\base_layer.py in assert_input_compatibility(self, inputs)
    309                                      self.name + ': expected ndim=' +
    310                                      str(spec.ndim) + ', found ndim=' +
--> 311                                      str(K.ndim(x)))
    312             if spec.max_ndim is not None:
    313                 ndim = K.ndim(x)

ValueError: Input 0 is incompatible with layer conv2d_1: expected ndim=4, found ndim=3
```

#### Training

```python
import pandas as pd
import keras
from autokeras import TextClassifier
from sklearn.model_selection import train_test_split
from keras.utils import plot_model
from keras.models import load_model

def read_csv(filename):
    data = pd.read_csv(filename, header=None)

    features = []
    labels = []
    for i in range(data[0].shape[0]):
        features.append(data[0][i])
        labels.append(data[1][i])
        
    return features, labels

filename = 'data/happiness.csv'
features, labels = read_csv(filename)
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, train_size=0.9, test_size=0.1)
classifier = TextClassifier(verbose=True)
classifier.fit(x=train_features, y=train_labels, time_limit=2 * 60)
classifier.final_fit(train_features, train_labels, test_features, test_labels, retrain=True)
y = classifier.evaluate(test_features, test_labels)
print(y)
```

#### Export keras model

```python
from keras.utils import plot_model
from keras.models import load_model

model_filename = 'models/text_model.h5'
classifier.export_keras_model(model_filename)
```

### Expected Behavior

It should export a keras model in normally.

### Setup Details

Include the details about the versions of:

 - OS type and version: Windows 10
 - Python: Python3.6
 - autokeras: 0.3.5
 - scikit-learn: 0.20.1
 - numpy: 1.15.4
 - keras: 2.2.2
 - scipy: 1.1.0
 - tensorflow: 1.10.0
 - pytorch: 1.0.0

**Comment by JY00002** [comment]
In case of using ImageClassifier, i also get :
TypeError:'NoneType' object is not callable.
any one can help?

**Comment by JY00002** [comment]
@lhideki you can refer the 'portable_load.py' in the dir"autokeras-master/examples", and i use solve my problem. hope the code can help you .
    MODEL_DIR = 'The_best_model.h5'
    clf.export_autokeras_model(MODEL_DIR)
    model = pickle_from_file(MODEL_DIR)

**Comment by lhideki** [comment]
If exporting as PyTorch model, I could do that like this.

```python
import torch

model_filename = 'models/text_model.h5'

model = classifier.cnn.best_model.produce_model()
torch.save(model, model_filename)
```

**Comment by Nicomedes89E** [comment]
Is there some improvement about this issue?

**Comment by songqiqqq** [comment]
ImageRegressor1D has the same error. Although the model can be fitted in autokeras, however, when export_keras_model, similar error is raised:
```
Traceback (most recent call last):
  File "src/squtils/tmp.py", line 113, in <module>
    clf.export_keras_model('mybest.graph')
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/autokeras/supervised.py", line 196, in export_keras_model
    self.cnn.best_model.produce_keras_model().save(model_file_name)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/autokeras/nn/graph.py", line 577, in produce_keras_model
    return KerasModel(self).model
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/autokeras/nn/graph.py", line 728, in __init__
    temp_tensor = keras_layer(edge_input_tensor)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/keras/engine/base_layer.py", line 414, in __call__
    self.assert_input_compatibility(inputs)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/keras/engine/base_layer.py", line 311, in assert_input_compatibility
    str(K.ndim(x)))
ValueError: Input 0 is incompatible with layer conv2d_1: expected ndim=4, found ndim=3

```
conv1d is used in the model(this can be confirmed by the output info. ).  
However , when exporting to keras model, it uses conv2d.
It seems like the export_keras_model only supports ImageClassifier/ImageRegressor.
@jhfjhfj1

**Comment by songqiqqq** [comment]
I changed some code in  autokeras.nn.layers.LayerType and autokeras.nn.layers.to_real_keras_layer. Now it satisfied my requirements to export keras model for  the case of ImageRegressor1D.

**Comment by William8Work** [comment]
Same issues here. How to export model for TextClassifier?

**Comment by collinskatie** [comment]
I am also unable to export the keras model for ImageRegressor1D - has any progress been made on solving this issue? Thanks!

**Comment by yfq512** [comment]
@lhideki I have the same question when I use StructuredDataClassifier,Do you solve it?
