### ISSUE TITLE
The question about model loading

### ISSUE THREAD

**Issue by asdzxc14** [keras-team/autokeras#433]
Hi, I have a question as following while I run the tasks:
There is always an error when loading the model. How to fix it?

```
Traceback (most recent call last):
  File "/home/xujinliang/yuanchao/mnist_test/mnist_test.py", line 25, in <module>
    model = load_model('my_model.h5')
  File "/home/xujinliang/anaconda3/envs/xyc36/lib/python3.6/site-packages/keras/engine/saving.py", line 249, in load_model
    f = h5py.File(filepath, mode='r')
  File "/home/xujinliang/anaconda3/envs/xyc36/lib/python3.6/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/home/xujinliang/anaconda3/envs/xyc36/lib/python3.6/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

My code on mnist dataset
```
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(x_train.shape + (1,))
x_test = x_test.reshape(x_test.shape + (1,))

clf = ImageClassifier(verbose=True, augment=False)
clf.fit(x_train, y_train, time_limit=0.5 * 60 * 60)
clf.final_fit(x_train, y_train, x_test, y_test, retrain=True)
y = clf.evaluate(x_test, y_test)
print(y)

clf.export_autokeras_model('my_model.h5')
model = load_model('my_model.h5')

plot_model(model, to_file='my_model.png')
```

**Comment by hemangjoshi37a** [comment]
Upgrade all pip packages will solve the problem.

**Comment by CongFang** [comment]
Use the following code to loading saved "autokeras_model":

 ```
from autokeras.utils import pickle_from_file
 autokeras_model = pickle_from_file("20170506mnist_autokeras_best_model.h5")
 autokeras_score = autokeras_model.evaluate(x_test, y_test)
 print(autokeras_score)
```
