### ISSUE TITLE
Runtime errors occur when the input data has many dimensions (my data has 10)

### ISSUE THREAD

**Issue by ycd2016** [keras-team/autokeras#461]
### Bug Description

**The shape of my input data is [batch,32,32,10]** and then a runtime error occurs while training model 0.
This is an exception that is thrown out of the Pytorch: **running_mean should contain 3 elements, not 10.**

### Reproducing Steps
Steps to reproduce the behaviour:
  * Step 1: See the code below...
  * Step 2: ...

### Expected Behavior

I'm not sure but there's something wrong here. The running_mean of the BatchNorm layer that is transmitted to Pytorch should be the same as the dimension of the input data. 

### Setup Details
Include the details about the versions of:
 - OS type and version: Ubuntu 16.04 LTS
 - Python: 3.6
 - autokeras: 0.3.5
 - tensorflow: 1.12
 - pytorch: 0.4.1

### Additional context

Part of my code:
**The shape of x_train, x_test is [batch,32,32,10]**
```
if __name__ == '__main__':
    x_train, y_train = data_generater(data_path="./train.h5")
    x_test, y_test = data_generater(data_path="./validation.h5")
    y_train = numpy.argmax(y_train, axis=1)
    y_test = numpy.argmax(y_test, axis=1)
    clf = ImageClassifier(path="./models/",
                          verbose=True,
                          searcher_args={'input_shape': (32, 32, 10)})
    clf.fit(x_train, y_train, time_limit=90 * 60)
    clf.final_fit(x_train, y_train, x_test, y_test,
                  trainer_args={'max_no_improvement_num': 5},
                  retrain=False)
    clf.export_keras_model('model_best.h5')
    print(clf.evaluate(x_test, y_test))
```
All logs:
```
Using TensorFlow backend.
Preprocessing the images.
Preprocessing finished.

Initializing search.
Initialization finished.


+----------------------------------------------+
|               Training model 0               |
+----------------------------------------------+
Using TensorFlow backend.
Epoch-1, Current Metric - 0:   0%|                                        | 0/2 [00:00<?, ? batch/s]Process SpawnProcess-1:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/root/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/autokeras/search.py", line 277, in train
    raise e
  File "/root/anaconda3/lib/python3.6/site-packages/autokeras/search.py", line 270, in train
    verbose=verbose).train_model(**trainer_args)
  File "/root/anaconda3/lib/python3.6/site-packages/autokeras/nn/model_trainer.py", line 126, in train_model
    self._train()
  File "/root/anaconda3/lib/python3.6/site-packages/autokeras/nn/model_trainer.py", line 160, in _train
    outputs = self.model(inputs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/autokeras/nn/graph.py", line 681, in forward
    temp_tensor = torch_layer(edge_input_tensor)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 66, in forward
    exponential_average_factor, self.eps)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1254, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: running_mean should contain 3 elements not 10
```

**Comment by dzimmerman-nci** [comment]
what was the resolution for this?
