### ISSUE TITLE
Unable to resume search/training from previously trained model

### ISSUE THREAD

**Issue by savan77** [keras-team/autokeras#485]
I searched and trained a model on cats-dogs dataset few days ago. Now, I want to search for better model and want to use previously trained model as a starting point. As far as I know, I can use `resume` parameter of `ImageClassifier` class to load model from specified `path`. I verified that the `path` contains all files including `classifier` and `module`. 

When I try searching/training again I get the following error.

```
Traceback (most recent call last):
  File "from_images.py", line 12, in <module>
    clf.fit(x_train, y_train, time_limit= 10 * 60 * 60)
  File "/home/onepanel/.conda/lib/python3.6/site-packages/autokeras/image/image_supervised.py", line 111, in fit
    super().fit(x, y, time_limit)
  File "/home/onepanel/.conda/lib/python3.6/site-packages/autokeras/supervised.py", line 135, in fit
    self.cnn.fit(self.get_n_output_node(), x_train.shape, train_data, test_data, time_limit)
  File "/home/onepanel/.conda/lib/python3.6/site-packages/autokeras/net_module.py", line 72, in fit
    self.searcher.search(train_data, test_data, int(time_remain))
  File "/home/onepanel/.conda/lib/python3.6/site-packages/autokeras/search.py", line 149, in search
    graph, other_info, model_id = self.training_queue.pop(0)
IndexError: pop from empty list
```
which suggests that it could not load previously trained model. I am not sure if it is a bug or an issue.

Thanks

**Comment by xujiameng** [comment]
I encountered the same problem. I could not use fit after importing the model, but final_fit or evaluate could be used.
