### ISSUE TITLE
CnnModule: ValueError: 

### ISSUE THREAD

**Issue by sameedmsiddiqui** [keras-team/autokeras#500]
### Bug Description
When running CnnModule (see below for code), I get the following error:

```
Process ForkProcess-1:
Traceback (most recent call last):
  File "/home/sameed/anaconda3/envs/autokeras/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/sameed/anaconda3/envs/autokeras/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sameed/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/search.py", line 343, in train
    verbose=verbose).train_model(**trainer_args)
  File "/home/sameed/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/nn/model_trainer.py", line 137, in train_model
    self._train()
  File "/home/sameed/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/nn/model_trainer.py", line 173, in _train
    outputs = self.model(inputs)
  File "/home/sameed/anaconda3/envs/autokeras/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sameed/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/nn/graph.py", line 686, in forward
    temp_tensor = torch_layer(edge_input_tensor)
  File "/home/sameed/anaconda3/envs/autokeras/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sameed/anaconda3/envs/autokeras/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 60, in forward
    self._check_input_dim(input)
  File "/home/sameed/anaconda3/envs/autokeras/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 169, in _check_input_dim
    .format(input.dim()))
ValueError: expected 2D or 3D input (got 4D input)

```

### Reproducing Steps
```python
class RnaSeqDataset(Dataset):
    def __init__(self, x_data, y_data):
        """
        Args:
        """
        self.x_data = x_data
        self.y_data = y_data
    def __len__(self):
        return len(self.x_data)
    def __getitem__(self, idx):
        return self.x_data[idx], self.y_data[idx]


seq_train, seq_test, mfe_train, mfe_test = train_test_split(seqs_one_hot, encoded_mfes, test_size=0.15, random_state=42) # seq_train.shape returns (1700, 4, 59, 1), mfe_train.shape returns (1700, 4, 59, 1)
print("Finished encoding mfes")
params = {
    'batch_size' : 64,
    'shuffle': True,
    'num_workers': 0}
train_data = RnaSeqDataset(seq_train, mfe_train)
training_generator = DataLoader(train_data, **params)
test_data = RnaSeqDataset(seq_test, mfe_test)
testing_generator = DataLoader(test_data, **params)

test_folder = "cnn_autokeras"
cnn_module = CnnModule(loss=classification_loss, metric=Accuracy, searcher_args={}, path=test_folder,
                       verbose=False)
print("begin fitting")
cnn_module.fit(num_classes, (4, 59, 1), training_generator, testing_generator, time_limit=7 * 60 * 60)

```

### Expected Behavior
I expect the CnnModule to begin training.

### Setup Details
Include the details about the versions of:
 - OS type and version:
 - Python: 3.6
 - autokeras: 0.36
 - scikit-learn: 0.20.1
 - numpy: 1.15.4
 - keras: 2.2.4
 - scipy: 1.1.0
 - tensorflow: 1.10.0
 - pytorch: 1.0.0

Thanks a ton.

**Comment by codender** [comment]
Are the dimensions of (4, 59, 1) and training_generator equal?

**Comment by kapsl** [comment]
When I'm trying to train the Cnn Module I have:
nr_output_nodes = 8
input_shape (2749, 1, 12)

dataloader dataset: (232, 2749, 1, 12)
dataloader labels: (232, 8)

(i also tried using the same data for the test dataloader, to not make any mistake here)

i get the error message: RuntimeError: running_mean should contain 2749 elements not 12

See also https://github.com/jhfjhfj1/autokeras/issues/475
