### ISSUE TITLE
Negative dimension size bug caused by  produce_keras_model method

### ISSUE THREAD

**Issue by songqiqqq** [keras-team/autokeras#545]
### Bug Description
I use ImageRegressor to fit my data with shape [?, hight=5, width=20, channel=1]. At the stage of fitting, everything is ok.  However, at the end,  when I use clf.export_keras_model method to export the keras version model, the error is raised:

tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 2 from 1 for 'max_pooling2d_3/MaxPool' (op: 'MaxPool') with input shapes: [?,1,5,64].

I suspect it's related to the parameter of data_format (= 'tf' or 'th'), but I do not know how to fix it .

the whole error info is listed as below:

````
2019-02-19 16:09:49.161921: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
Traceback (most recent call last):
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1628, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 2 from 1 for 'max_pooling2d_3/MaxPool' (op: 'MaxPool') with input shapes: [?,1,5,64].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/squtils/tmp.py", line 110, in <module>
    clf.export_keras_model('mybest.graph')
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/autokeras/supervised.py", line 196, in export_keras_model
    self.cnn.best_model.produce_keras_model().save(model_file_name)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/autokeras/nn/graph.py", line 577, in produce_keras_model
    return KerasModel(self).model
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/autokeras/nn/graph.py", line 731, in __init__
    temp_tensor = keras_layer(edge_input_tensor)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/keras/layers/pooling.py", line 205, in call
    data_format=self.data_format)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/keras/layers/pooling.py", line 268, in _pooling_function
    pool_mode='max')
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3978, in pool2d
    data_format=tf_data_format)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2140, in max_pool
    name=name)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 4641, in max_pool
    data_format=data_format, name=name)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1792, in __init__
    control_input_ops)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1631, in _create_c_op
    raise ValueError(str(e))
ValueError: Negative dimension size caused by subtracting 2 from 1 for 'max_pooling2d_3/MaxPool' (op: 'MaxPool') with input shapes: [?,1,5,64]. 
````
### Setup Details
Include the details about the versions of:
 - OS type and version:linux,
 - Python: 3.6
 - autokeras: 0.3.7
 - scikit-learn:
 - numpy:
 - keras:2.2.4
 - scipy:
 - tensorflow:1.10.1
 - torch:0.4.0

**Comment by songqiqqq** [comment]
Maybe not the problem of data_format parameter. I found some graphs also raise the same error with the input the shape of [? , x, 1, x]. The third value should not the be the channel neither in 'th' nor in 'tf' style. 

what messed me up is  why the network is valid in autokeras, but not valid in keras or tensorflow.

really appreciate for the help.

**Comment by songqiqqq** [comment]
I suspect whether the autokeras only support the data with the same width and high ?

**Comment by songqiqqq** [comment]
when I change the autokeras version to 0.2.13,  the similar error is raised at the fitting stage:
```
Using TensorFlow backend.
get feature done ......
.......................................

Initializing search.
Initialization finished.


╒==============================================╕
|               Training model 0               |
╘==============================================╛
Using TensorFlow backend.
                                                                           /home/qsong/.conda/envs/py36/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/qsong/.conda/envs/py36/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/qsong/.conda/envs/py36/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/autokeras/search.py", line 280, in train
    verbose).train_model(**trainer_args)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/autokeras/utils.py", line 126, in train_model
    self._train()
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/autokeras/utils.py", line 170, in _train
    outputs = self.model(inputs)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/autokeras/graph.py", line 610, in forward
    temp_tensor = torch_layer(edge_input_tensor)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 142, in forward
    self.return_indices)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/torch/nn/functional.py", line 396, in max_pool2d
    ret = torch._C._nn.max_pool2d_with_indices(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: Given input size: (64x1x1). Calculated output size: (64x0x0). Output size is too small at /pytorch/aten/src/THCUNN/generic/SpatialDilatedMaxPooling.cu:69
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/squtils/tmp.py", line 102, in <module>
    clf.fit(feature_is, label_is, time_limit= 5 * 60)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/autokeras/image_supervised.py", line 239, in fit
    run_searcher_once(train_data, test_data, self.path, int(time_remain))
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/autokeras/image_supervised.py", line 40, in run_searcher_once
    searcher.search(train_data, test_data, timeout)
  File "/home/qsong/.conda/envs/py36/lib/python3.6/site-packages/autokeras/search.py", line 210, in search
    metric_value, loss, graph = train_results.get(timeout=remaining_time)[0]
  File "/home/qsong/.conda/envs/py36/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
RuntimeError: Given input size: (64x1x1). Calculated output size: (64x0x0). Output size is too small at /pytorch/aten/src/THCUNN/generic/SpatialDilatedMaxPooling.cu:69

```
it seems like there is a lower limit of image dimension,  (as stated in this issue by [jhfjhfj1](/jhfjhfj1) https://github.com/jhfjhfj1/autokeras/issues/310#issuecomment-455797664).
