### ISSUE TITLE
RuntimeError: CUDA error: unspecified launch failure

### ISSUE THREAD

**Issue by CongFang** [keras-team/autokeras#626]
### Configurations

tensorflow 1.10.0
CUDA 9.0
cudnn 7.0.5

### My code
`clf = ImageClassifier1D(verbose=True, augment=False)
    clf.fit(x_train, y_train, time_limit=60 * 60 * 3)
    clf.final_fit(x_train, y_train, x_test, y_test, retrain=True)
    y = clf.evaluate(x_test, y_test)
    print(y * 100)`

### error information
+----------------------------------------------+
|               Training model 1               |
+----------------------------------------------+
Epoch-7, Current Metric - 0.984:  48%|############             | 50/104 [05:31<05:38,  6.27s/ batch]Time is out.
Traceback (most recent call last):
  File "auto_iNose.py", line 52, in <module>
    clf.final_fit(x_train, y_train, x_test, y_test, retrain=True)
  File "/home/cfang/anaconda3/envs/iNose/lib/python3.6/site-packages/autokeras/supervised.py", line 211, in final_fit
    self.cnn.final_fit(train_data, test_data, trainer_args, retrain)
  File "/home/cfang/anaconda3/envs/iNose/lib/python3.6/site-packages/autokeras/net_module.py", line 104, in final_fit
    self.path)
  File "/home/cfang/anaconda3/envs/iNose/lib/python3.6/site-packages/autokeras/search.py", line 363, in train
    raise e
  File "/home/cfang/anaconda3/envs/iNose/lib/python3.6/site-packages/autokeras/search.py", line 356, in train
    verbose=verbose).train_model(**trainer_args)
  File "/home/cfang/anaconda3/envs/iNose/lib/python3.6/site-packages/autokeras/backend/__init__.py", line 21, in get_model_trainer
    return cls.backend.ModelTrainer(**kwargs)
  File "/home/cfang/anaconda3/envs/iNose/lib/python3.6/site-packages/autokeras/backend/torch/model_trainer.py", line 62, in __init__
    self.model.to(self.device)
  File "/home/cfang/anaconda3/envs/iNose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/home/cfang/anaconda3/envs/iNose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/cfang/anaconda3/envs/iNose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)
  File "/home/cfang/anaconda3/envs/iNose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 379, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: unspecified launch failure

**Comment by LiDaiY** [comment]
I encounter the same error, could please tell me how to solve this if you had solved the problem. Thank you
