### ISSUE TITLE
RuntimeError when running CIFAR10 example

### ISSUE THREAD

**Issue by Fridgi** [keras-team/autokeras#665]
**Error Description**
I'm running the getting started example on my GPU and Autokeras works well when training the first 2 models of the CIFAR10. However, it seems that when Autokeras wants to train the 3rd model, here comes the error. So how can I fix that? 

    Traceback (most recent call last):
      File "/home/shuhao/anaconda3/envs/autokeras/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
        self.run()
      File "/home/shuhao/anaconda3/envs/autokeras/lib/python3.6/multiprocessing/process.py", line 93, in run
        self._target(*self._args, **self._kwargs)
      File "/home/shuhao/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/search.py", line 363, in train
        raise e
      File "/home/shuhao/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/search.py", line 356, in train
        verbose=verbose).train_model(**trainer_args)
      File "/home/shuhao/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/backend/torch/model_trainer.py", line 109, in train_model
        self._train()
      File "/home/shuhao/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/backend/torch/model_trainer.py", line 145, in _train
        outputs = self.model(inputs)
      File "/home/shuhao/anaconda3/envs/autokeras/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
        result = self.forward(*input, **kwargs)
      File "/home/shuhao/anaconda3/envs/autokeras/lib/python3.6/site-packages/autokeras/backend/torch/model.py", line 51, in forward
        temp_tensor = torch_layer(edge_input_tensor)
      File "/home/shuhao/anaconda3/envs/autokeras/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
        result = self.forward(*input, **kwargs)
      File "/home/shuhao/anaconda3/envs/autokeras/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 638, in forward
        self.padding, self.ceil_mode, self.count_include_pad)
    RuntimeError: invalid argument 2: input image (T: 15 H: 15 W: 1) smaller than kernel size (kT: 2 kH: 2 kW: 2) at /pytorch/aten/src/THCUNN/generic/VolumetricAveragePooling.cu:57

**Setup Environment**
Ubuntu 16.04 
Python 3.6
Autokeras 0.4.0
CUDA 7.5

**Comment by wala-nias** [comment]
Hi, I have the same problem, @Fridgi did you find a solution for it ?
