### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by ozoraa** [keras-team/autokeras#713]
Hey there, I'm quite new to Autokeras and I wanted to start with one of the examples (mnist.py) but there is raised an error:

Traceback (most recent call last):
  File "mnist.py", line 8, in <module>
    clf = ImageClassifier(verbose=True, augment=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autokeras\task.py", line 16, in __init__
    super().__init__(hyper_head.ClassificationHead(), **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autokeras\task.py", line 11, in __init__
    **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autokeras\auto_model.py", line 42, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'verbose'

So I deleted the "verbose" parameter out of the ImageClassifier, same happens with the argument "augment". Deleted it too. Now there is a new error:

Traceback (most recent call last):
  File "mnist.py", line 9, in <module>
    clf.fit(x_train, y_train, time_limit=30 * 60)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autokeras\auto_model.py", line 237, in fit
    validation_split=validation_split)
  File "C:\ProgramData\Anaconda3\lib\site-packages\autokeras\auto_model.py", line 287, in prepare_data
    x_val, y_val = validation_data
TypeError: cannot unpack non-iterable NoneType object

What am I doing wrong? o.O
Thanks!

**Comment by ozoraa** [comment]
Okay sorry I kind of ignored the hint of AutoKeras being only compatible with Python 3.6...

**Comment by yellow1996** [comment]
even i'm getting the same issue. Any workaround for this ?
