### ISSUE TITLE
RuntimeError: Given groups=1, weight of size 

### ISSUE THREAD

**Issue by MaxKinny** [keras-team/autokeras#717]
### Bug Description

Whenever I fit the model, after several searches, it will always raise follow issue：
```
+----------------------------------------------+
|              Training model 66               |
+----------------------------------------------+
Epoch-1, Current Metric - 0:   0%|                                       | 0/80 [00:00<?, ? batch/s]
Epoch-1, Current Metric - 0:  12%|███▊                          | 10/80 [00:01<00:07,  9.03 batch/s]
Epoch-1, Current Metric - 0:  25%|███████▌                      | 20/80 [00:01<00:05, 10.08 batch/s]
Epoch-1, Current Metric - 0:  38%|███████████▎                  | 30/80 [00:02<00:04, 10.95 batch/s]
Epoch-1, Current Metric - 0:  50%|███████████████               | 40/80 [00:03<00:03, 11.65 batch/s]
Epoch-1, Current Metric - 0:  62%|██████████████████▊           | 50/80 [00:04<00:02, 12.20 batch/s]
Epoch-1, Current Metric - 0:  75%|██████████████████████▌       | 60/80 [00:04<00:01, 12.61 batch/s]
Epoch-1, Current Metric - 0:  88%|██████████████████████████▎   | 70/80 [00:05<00:00, 12.92 batch/s]
Epoch-1, Current Metric - 0: 100%|██████████████████████████████| 80/80 [00:06<00:00, 13.15 batch/s]
                                                                                                    
Epoch-1, Current Metric - 0:   0%|                                        | 0/4 [00:00<?, ? batch/s]
                                                                                                    
Epoch-2, Current Metric - 0.802:   0%|                                   | 0/80 [00:00<?, ? batch/s]
Epoch-2, Current Metric - 0.802:  12%|███▎                      | 10/80 [00:00<00:05, 12.10 batch/s]
Epoch-2, Current Metric - 0.802:  25%|██████▌                   | 20/80 [00:01<00:04, 12.55 batch/s]
Epoch-2, Current Metric - 0.802:  38%|█████████▊                | 30/80 [00:02<00:03, 12.88 batch/s]
Epoch-2, Current Metric - 0.802:  50%|█████████████             | 40/80 [00:03<00:03, 13.12 batch/s]
Epoch-2, Current Metric - 0.802:  62%|████████████████▎         | 50/80 [00:03<00:02, 13.28 batch/s]
Epoch-2, Current Metric - 0.802:  75%|███████████████████▌      | 60/80 [00:04<00:01, 13.41 batch/s]
Epoch-2, Current Metric - 0.802:  88%|██████████████████████▊   | 70/80 [00:05<00:00, 13.49 batch/s]
Epoch-2, Current Metric - 0.802: 100%|██████████████████████████| 80/80 [00:05<00:00, 13.56 batch/s]
                                                                                                    
Epoch-2, Current Metric - 0.802:   0%|                                    | 0/4 [00:00<?, ? batch/s]
                                                                                                    
Epoch-3, Current Metric - 0.802:   0%|                                   | 0/80 [00:00<?, ? batch/s]
Epoch-3, Current Metric - 0.802:  12%|███▎                      | 10/80 [00:00<00:05, 12.22 batch/s]
Epoch-3, Current Metric - 0.802:  25%|██████▌                   | 20/80 [00:01<00:04, 12.64 batch/s]
Epoch-3, Current Metric - 0.802:  38%|█████████▊                | 30/80 [00:02<00:03, 12.94 batch/s]
Epoch-3, Current Metric - 0.802:  50%|█████████████             | 40/80 [00:03<00:03, 13.16 batch/s]
Epoch-3, Current Metric - 0.802:  62%|████████████████▎         | 50/80 [00:03<00:02, 13.32 batch/s]
Epoch-3, Current Metric - 0.802:  75%|███████████████████▌      | 60/80 [00:04<00:01, 13.44 batch/s]
Epoch-3, Current Metric - 0.802:  88%|██████████████████████▊   | 70/80 [00:05<00:00, 13.50 batch/s]
Epoch-3, Current Metric - 0.802: 100%|██████████████████████████| 80/80 [00:05<00:00, 13.56 batch/s]
                                                                                                    
Epoch-3, Current Metric - 0.802:   0%|                                    | 0/4 [00:00<?, ? batch/s]
                                                                                                    
Epoch-4, Current Metric - 0.786:   0%|                                   | 0/80 [00:00<?, ? batch/s]
Epoch-4, Current Metric - 0.786:  12%|███▎                      | 10/80 [00:00<00:06, 11.14 batch/s]
Epoch-4, Current Metric - 0.786:  25%|██████▌                   | 20/80 [00:01<00:05, 11.80 batch/s]
Epoch-4, Current Metric - 0.786:  38%|█████████▊                | 30/80 [00:02<00:04, 12.32 batch/s]
Epoch-4, Current Metric - 0.786:  50%|█████████████             | 40/80 [00:03<00:03, 12.70 batch/s]
Epoch-4, Current Metric - 0.786:  62%|████████████████▎         | 50/80 [00:03<00:02, 12.97 batch/s]
Epoch-4, Current Metric - 0.786:  75%|███████████████████▌      | 60/80 [00:04<00:01, 13.18 batch/s]
Epoch-4, Current Metric - 0.786:  88%|██████████████████████▊   | 70/80 [00:05<00:00, 13.33 batch/s]
Epoch-4, Current Metric - 0.786: 100%|██████████████████████████| 80/80 [00:06<00:00, 13.44 batch/s]
                                                                                                    
Epoch-4, Current Metric - 0.786:   0%|                                    | 0/4 [00:00<?, ? batch/s]
                                                                                                    
Epoch-5, Current Metric - 0.794:   0%|                                   | 0/80 [00:00<?, ? batch/s]
Epoch-5, Current Metric - 0.794:  12%|███▎                      | 10/80 [00:00<00:05, 12.13 batch/s]
Epoch-5, Current Metric - 0.794:  25%|██████▌                   | 20/80 [00:01<00:04, 12.57 batch/s]
Epoch-5, Current Metric - 0.794:  38%|█████████▊                | 30/80 [00:02<00:03, 12.88 batch/s]
Epoch-5, Current Metric - 0.794:  50%|█████████████             | 40/80 [00:03<00:03, 13.12 batch/s]
Epoch-5, Current Metric - 0.794:  62%|████████████████▎         | 50/80 [00:03<00:02, 13.29 batch/s]
Epoch-5, Current Metric - 0.794:  75%|███████████████████▌      | 60/80 [00:04<00:01, 13.39 batch/s]
Epoch-5, Current Metric - 0.794:  88%|██████████████████████▊   | 70/80 [00:05<00:00, 13.48 batch/s]
Epoch-5, Current Metric - 0.794: 100%|██████████████████████████| 80/80 [00:05<00:00, 13.54 batch/s]
                                                                                                    
Epoch-5, Current Metric - 0.794:   0%|                                    | 0/4 [00:00<?, ? batch/s]
                                                                                                    
Epoch-6, Current Metric - 0.798:   0%|                                   | 0/80 [00:00<?, ? batch/s]
Epoch-6, Current Metric - 0.798:  12%|███▎                      | 10/80 [00:00<00:05, 11.80 batch/s]
Epoch-6, Current Metric - 0.798:  25%|██████▌                   | 20/80 [00:01<00:04, 12.31 batch/s]
Epoch-6, Current Metric - 0.798:  38%|█████████▊                | 30/80 [00:02<00:03, 12.70 batch/s]
Epoch-6, Current Metric - 0.798:  50%|█████████████             | 40/80 [00:03<00:03, 12.99 batch/s]
Epoch-6, Current Metric - 0.798:  62%|████████████████▎         | 50/80 [00:03<00:02, 13.19 batch/s]
Epoch-6, Current Metric - 0.798:  75%|███████████████████▌      | 60/80 [00:04<00:01, 13.34 batch/s]
Epoch-6, Current Metric - 0.798:  88%|██████████████████████▊   | 70/80 [00:05<00:00, 13.44 batch/s]
Epoch-6, Current Metric - 0.798: 100%|██████████████████████████| 80/80 [00:05<00:00, 13.51 batch/s]
                                                                                                    
Epoch-6, Current Metric - 0.798:   0%|                                    | 0/4 [00:00<?, ? batch/s]
                                                                                                    
Epoch-7, Current Metric - 0.802:   0%|                                   | 0/80 [00:00<?, ? batch/s]
Epoch-7, Current Metric - 0.802:  12%|███▎                      | 10/80 [00:00<00:05, 11.67 batch/s]
Epoch-7, Current Metric - 0.802:  25%|██████▌                   | 20/80 [00:01<00:04, 12.22 batch/s]
Epoch-7, Current Metric - 0.802:  38%|█████████▊                | 30/80 [00:02<00:03, 12.63 batch/s]
Epoch-7, Current Metric - 0.802:  50%|█████████████             | 40/80 [00:03<00:03, 12.94 batch/s]
Epoch-7, Current Metric - 0.802:  62%|████████████████▎         | 50/80 [00:03<00:02, 13.15 batch/s]
Epoch-7, Current Metric - 0.802:  75%|███████████████████▌      | 60/80 [00:04<00:01, 13.31 batch/s]
Epoch-7, Current Metric - 0.802:  88%|██████████████████████▊   | 70/80 [00:05<00:00, 13.43 batch/s]
Epoch-7, Current Metric - 0.802: 100%|██████████████████████████| 80/80 [00:05<00:00, 13.51 batch/s]
                                                                                                    
Epoch-7, Current Metric - 0.802:   0%|                                    | 0/4 [00:00<?, ? batch/s]
                                                                                                    
Epoch-8, Current Metric - 0.8:   0%|                                     | 0/80 [00:00<?, ? batch/s]
Epoch-8, Current Metric - 0.8:  12%|███▌                        | 10/80 [00:00<00:06, 11.64 batch/s]
Epoch-8, Current Metric - 0.8:  25%|███████                     | 20/80 [00:01<00:04, 12.19 batch/s]
Epoch-8, Current Metric - 0.8:  38%|██████████▌                 | 30/80 [00:02<00:03, 12.60 batch/s]
Epoch-8, Current Metric - 0.8:  50%|██████████████              | 40/80 [00:03<00:03, 12.92 batch/s]
Epoch-8, Current Metric - 0.8:  62%|█████████████████▌          | 50/80 [00:03<00:02, 13.13 batch/s]
Epoch-8, Current Metric - 0.8:  75%|█████████████████████       | 60/80 [00:04<00:01, 13.29 batch/s]
Epoch-8, Current Metric - 0.8:  88%|████████████████████████▌   | 70/80 [00:05<00:00, 13.41 batch/s]
Epoch-8, Current Metric - 0.8: 100%|████████████████████████████| 80/80 [00:05<00:00, 13.49 batch/s]
                                                                                                    
Epoch-8, Current Metric - 0.8:   0%|                                      | 0/4 [00:00<?, ? batch/s]
                                                                                                    
Epoch-9, Current Metric - 0.792:   0%|                                   | 0/80 [00:00<?, ? batch/s]
Epoch-9, Current Metric - 0.792:  12%|███▎                      | 10/80 [00:00<00:06, 11.48 batch/s]
Epoch-9, Current Metric - 0.792:  25%|██████▌                   | 20/80 [00:01<00:04, 12.07 batch/s]
Epoch-9, Current Metric - 0.792:  38%|█████████▊                | 30/80 [00:02<00:03, 12.52 batch/s]
Epoch-9, Current Metric - 0.792:  50%|█████████████             | 40/80 [00:03<00:03, 12.85 batch/s]
Epoch-9, Current Metric - 0.792:  62%|████████████████▎         | 50/80 [00:03<00:02, 13.09 batch/s]
Epoch-9, Current Metric - 0.792:  75%|███████████████████▌      | 60/80 [00:04<00:01, 13.27 batch/s]
Epoch-9, Current Metric - 0.792:  88%|██████████████████████▊   | 70/80 [00:05<00:00, 13.40 batch/s]
Epoch-9, Current Metric - 0.792: 100%|██████████████████████████| 80/80 [00:05<00:00, 13.48 batch/s]
                                                                                                    
Epoch-9, Current Metric - 0.792:   0%|                                    | 0/4 [00:00<?, ? batch/s]
                                                                                                    
No loss decrease after 5 epochs.
Saving model.
+--------------------------------------------------------------------------+
|        Model ID        |          Loss          |      Metric Value      |
+--------------------------------------------------------------------------+
|           66           |   1.8044039845466613   |         0.7964         |
+--------------------------------------------------------------------------+
+----------------------------------------------+
|              Training model 67               |
+----------------------------------------------+
Epoch-1, Current Metric - 0:   0%|                                       | 0/80 [00:00<?, ? batch/s]Process ForkProcess-68:
Traceback (most recent call last):
  File "/home/public/anaconda3/envs/auto-keras/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/public/anaconda3/envs/auto-keras/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/public/anaconda3/envs/auto-keras/lib/python3.6/site-packages/autokeras/search.py", line 363, in train
    raise e
  File "/home/public/anaconda3/envs/auto-keras/lib/python3.6/site-packages/autokeras/search.py", line 356, in train
    verbose=verbose).train_model(**trainer_args)
  File "/home/public/anaconda3/envs/auto-keras/lib/python3.6/site-packages/autokeras/backend/torch/model_trainer.py", line 109, in train_model
    self._train()
  File "/home/public/anaconda3/envs/auto-keras/lib/python3.6/site-packages/autokeras/backend/torch/model_trainer.py", line 145, in _train
    outputs = self.model(inputs)
  File "/home/public/anaconda3/envs/auto-keras/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/public/anaconda3/envs/auto-keras/lib/python3.6/site-packages/autokeras/backend/torch/model.py", line 51, in forward
    temp_tensor = torch_layer(edge_input_tensor)
  File "/home/public/anaconda3/envs/auto-keras/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/public/anaconda3/envs/auto-keras/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 187, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [2048, 6144, 1], expected input[128, 8192, 128] to have 6144 channels, but got 8192 channels instead
```
This is my code：
```
from autokeras import ImageClassifier
from matplotlib import pyplot as plt
import glob
from PIL import Image
import numpy as np

if __name__ == '__main__':
    picture_path = '../../../kaggle_SIIM-ACR-Pneumothorax-Segmentation/data/png/256/train/picture/*.png'
    mask_path = '../../../kaggle_SIIM-ACR-Pneumothorax-Segmentation/data/png/256/train/mask/*.png'
    train_files = glob.glob(picture_path)
    mask_files = glob.glob(mask_path)
    x_train = np.array([np.array(Image.open(fn)) for fn in train_files])
    y_train = []
    for fp in mask_files:
        if len(np.unique(Image.open(fp))) == 2:
            y_train.append(1)
        else:
            y_train.append(0)
    y_train = np.array(y_train)
    clf = ImageClassifier(verbose=True, augment=False)
    clf.fit(x_train, y_train, time_limit=30 * 6000) # x_train is a 4-dims numpy array, y_train is 1-dim numpy array
```

### Setup Details
Include the details about the versions of:
 - OS type and version:Unbuntu 16.04
 - Python: 3.6.8
 - autokeras: 0.4.0
 - scikit-learn: 0.20.2
 - numpy: 1.16.1
 - keras: 2.2.4
 - scipy: 1.2.0
 - tensorflow: 1.13.1
 - pytorch: 1.0.1.post2

**Comment by Haorotu** [comment]
I also meet the same issue. I please ask "Have you already worked out it ?"

**Comment by MaxKinny** [comment]
> I also meet the same issue. I please ask "Have you already worked out it ?"

Not yet, do you have any clue?
