### ISSUE TITLE
autokeras for "images" with more than 3 channels?

### ISSUE THREAD

**Issue by erap129** [keras-team/autokeras#722]
Hello, I tried using autokeras for data of shape (batch_size, 1125, 1, 22)
This is essentially a 1D image with 22 channels. When running ImageClassifier as-is I get the following traceback:
```
Epoch-1, Current Metric - 0:   0%|                                        | 0/3 [00:00<?, ? batch/s]Process ForkProcess-1:
Traceback (most recent call last):
  File "/home/eladr/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/eladr/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/eladr/anaconda3/lib/python3.6/site-packages/autokeras/search.py", line 363, in train
    raise e
  File "/home/eladr/anaconda3/lib/python3.6/site-packages/autokeras/search.py", line 356, in train
    verbose=verbose).train_model(**trainer_args)
  File "/home/eladr/anaconda3/lib/python3.6/site-packages/autokeras/backend/torch/model_trainer.py", line 109, in train_model
    self._train()
  File "/home/eladr/anaconda3/lib/python3.6/site-packages/autokeras/backend/torch/model_trainer.py", line 145, in _train
    outputs = self.model(inputs)
  File "/home/eladr/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eladr/anaconda3/lib/python3.6/site-packages/autokeras/backend/torch/model.py", line 51, in forward
    temp_tensor = torch_layer(edge_input_tensor)
  File "/home/eladr/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eladr/anaconda3/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 76, in forward
    exponential_average_factor, self.eps)
  File "/home/eladr/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1623, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: running_mean should contain 3 elements not 22
```
I was wondering if a tweak can be made by myself somewhere to support this data shape?
Thanks.

**Comment by yingkaisha** [comment]
I have issues with input shape (?, 64, 64, 2). Seems that ak only work with 1- and 3-channel gridded inputs.
