### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'seed'

### ISSUE THREAD

**Issue by GerardLiu96** [keras-team/autokeras#851]
### Setup Details
Include the details about the versions of:
 - OS type and version:Ubuntu 16.04
 - Python: 3.7.3
 - autokeras: 1.0.0
 - scikit-learn: 0.20.2
 - numpy: 1.16.1
 - keras: 2.1.1
 - scipy:1.2.0
 - tensorflow:2.0.0
 - pytorch:1.0.1

**Comment by GerardLiu96** [comment]
Traceback (most recent call last):
  File "auto.py", line 58, in <module>
    clf.fit(X_train, Y_train, validation_split=0.2)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/task.py", line 111, in fit
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/auto_model.py", line 159, in fit
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/tuner.py", line 132, in search
    super().search(callbacks=new_callbacks, **fit_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kerastuner/engine/base_tuner.py", line 122, in search
    self.run_trial(trial, *fit_args, **fit_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/tuner.py", line 46, in run_trial
    trial.hyperparameters)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/hypermodel/graph.py", line 435, in build_graphs
    plain_graph = self.hyper_build(hp)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/hypermodel/graph.py", line 455, in hyper_build
    outputs = old_block.build(hp, inputs=inputs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/hypermodel/base.py", line 65, in _build_wrapper
    return self._build(hp, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/hypermodel/hyperblock.py", line 69, in build
    seed=self.seed)(output_node)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/hypermodel/preprocessor.py", line 452, in __init__
    super().__init__(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autokeras/hypermodel/base.py", line 48, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'seed'

**Comment by GerardLiu96** [comment]
i find the bug, sorry....
