### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [256, 384, 1, 1], expected input[20, 512, 32, 32] to have 384 channels, but got 512 channels instead. Same as previous bug #351

### ISSUE THREAD

**Issue by kalufinnle** [keras-team/autokeras#869]
### Bug Description: It has been reported by numerous people at #351 
Bug Description
It will report an error halfway through.

+----------------------------------------------+
| Training model 54 |
+----------------------------------------------+
Using TensorFlow backend.
Epoch-1, Current Metric - 0: 0%| | 0/61 [00:00<?, ? batch/s]Process SpawnProcess-55:
Traceback (most recent call last):
File "/home/guost/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/home/guost/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "/home/guost/autokeras/Newversion/034/autokeras/autokeras/search.py", line 297, in train
verbose=verbose).train_model(**trainer_args)
File "/home/guost/autokeras/Newversion/034/autokeras/autokeras/nn/model_trainer.py", line 122, in train_model
self._train()
File "/home/guost/autokeras/Newversion/034/autokeras/autokeras/nn/model_trainer.py", line 156, in _train
outputs = self.model(inputs)
File "/home/guost/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in call
result = self.forward(*input, **kwargs)
File "/home/guost/autokeras/Newversion/034/autokeras/autokeras/nn/graph.py", line 677, in forward
temp_tensor = torch_layer(edge_input_tensor)
File "/home/guost/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in call
result = self.forward(*input, **kwargs)
File "/home/guost/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [256, 384, 1, 1], expected input[20, 512, 32, 32] to have 384 channels, but got 512 channels instead

My code：
if name == 'main':
train_data, train_labels = load_image_dataset(csv_file_path=TRAIN_CSV_DIR, images_path=TRAIN_IMG_DIR)
test_data, test_labels = load_image_dataset(csv_file_path=TEST_CSV_DIR, images_path=TEST_IMG_DIR)
train_data = train_data.astype('float32') / 255.
test_data = test_data.astype('float32') / 255.
clf = ImageClassifier(verbose=True,path='/home/guost/autokeras/Newversion/034/modelPath',resume=False)
clf.fit(train_data, train_labels, time_limit = 60 * 60)
clf.final_fit(train_data, train_labels, test_data, test_labels, retrain=True)
y = clf.evaluate(test_data, test_labels)
print("evaluate:", y)

My enviroment：
autokeras：'0.3.4'
python：3.6.6
torch:0.4.1
keras:2.2.4
tensorflow:1.12.0
system:Ubuntu16.04
numpy:1.15.2

**Comment by haifeng-jin** [comment]
It should be solved in the latest released version of AutoKeras.
