### ISSUE TITLE
Structured Data Classification example isn't working

### ISSUE THREAD

**Issue by mulka** [keras-team/autokeras#923]
### Bug Description

The simple example for Structured Data Classification in the tutorial isn't working for me.
https://autokeras.com/tutorial/structured_data_classification/

I'm getting this error when the predict call is made:
ValueError: Expect column_names to have length 10 but got 9.

### Reproducing Steps
  * Step 1: Download the titanic CSV files.
  * Step 2: Copy the simple example into a python script and modify the path to the CSV files
  * Step 3: Run the script

### Expected Behavior

I expected things to run smoothly without an error.

### Setup Details
Include the details about the versions of:
 - OS type and version: macOS Catalina 10.15.1
 - Python: 3.6.8
 - autokeras: 1.0.0 
 - scikit-learn: 0.22.1
 - numpy: 1.18.1
 - keras:
 - scipy: 1.4.1
 - tensorflow: 2.1.0
 - pytorch:

### Additional context

Traceback (most recent call last):
  File "titantic.py", line 12, in <module>
    predicted_y = clf.predict('eval.csv')
  File "/Users/mulka/Documents/Code/personal/autokeras/venv/lib/python3.6/site-packages/autokeras/task.py", line 542, in predict
    **kwargs)
  File "/Users/mulka/Documents/Code/personal/autokeras/venv/lib/python3.6/site-packages/autokeras/auto_model.py", line 287, in predict
    self._process_xy(x, None, predict=True))[0].batch(batch_size)
  File "/Users/mulka/Documents/Code/personal/autokeras/venv/lib/python3.6/site-packages/autokeras/auto_model.py", line 234, in _process_xy
    data = input_node.transform(data)
  File "/Users/mulka/Documents/Code/personal/autokeras/venv/lib/python3.6/site-packages/autokeras/hypermodel/node.py", line 46, in transform
    self._check(x)
  File "/Users/mulka/Documents/Code/personal/autokeras/venv/lib/python3.6/site-packages/autokeras/hypermodel/node.py", line 194, in _check
    actual=len(self.column_names)))
ValueError: Expect column_names to have length 10 but got 9.

**Comment by haifeng-jin** [comment]
Thank you for the report. We will fix this bug.

**Comment by haifeng-jin** [comment]
It is fixed in the latest release.
