### ISSUE TITLE
Customized Model example is not running

### ISSUE THREAD

**Issue by ikscapes** [keras-team/autokeras#958]
### Bug Description

Customized Model example (Implement New Block) is not working.

### Reproducing Steps
  * Step 1: Change error line -> solved
import autokeras as ak
import tensorflow as tf

class SingleDenseLayerBlock(ak.Block):

    def build(self, hp, inputs=None):
        # Get the input_node from inputs.
        input_node = tf.python.util.nest.flatten(inputs)[0] -> tf.nest.flatten(inputs)[0]
        layer = tf.keras.layers.Dense(
            hp.Int('num_units', min_value=32, max_value=512, step=32))
        output_node = layer(input_node)
        return output_node
  * Step 2: Execute code -> training the model was performed, but an error occurred in the evaluation line.

# Build the AutoModel
input_node = ak.Input()
output_node = SingleDenseLayerBlock()(input_node)
output_node = ak.RegressionHead()(output_node)
auto_model = ak.AutoModel(input_node, output_node, max_trials=10)
### Prepare Data
num_instances = 100
x_train = np.random.rand(num_instances, 20).astype(np.float32)
y_train = np.random.rand(num_instances, 1).astype(np.float32)
x_test = np.random.rand(num_instances, 20).astype(np.float32)
y_test = np.random.rand(num_instances, 1).astype(np.float32)
# Train the model
auto_model.fit(x_train, y_train)
**print(auto_model.evaluate(x_test, y_test)) -> error!**

The full error log is shown below.
Traceback (most recent call last):
  File "D:/Ikjoo/Tensorflow Projects/AutoML/autokeras_example.py", line 39, in <module>
    print(auto_model.evaluate(x_test, y_test))
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\autokeras\auto_model.py", line 366, in evaluate
    return self.tuner.get_best_model().evaluate(x=dataset, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\autokeras\engine\tuner.py", line 37, in get_best_model
    model = super().get_best_models()[0]
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\kerastuner\engine\tuner.py", line 231, in get_best_models
    return super(Tuner, self).get_best_models(num_models)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\kerastuner\engine\base_tuner.py", line 238, in get_best_models
    models = [self.load_model(trial) for trial in best_trials]
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\kerastuner\engine\base_tuner.py", line 238, in <listcomp>
    models = [self.load_model(trial) for trial in best_trials]
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\kerastuner\engine\tuner.py", line 157, in load_model
    trial.trial_id, best_epoch))
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 234, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1193, in load_weights
    status = self._trackable_saver.restore(filepath)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\tracking\util.py", line 1283, in restore
    checkpoint=checkpoint, proto_id=0).restore(self._graph_view.root)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 209, in restore
    restore_ops = trackable._restore_from_checkpoint_position(self)  # pylint: disable=protected-access
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 908, in _restore_from_checkpoint_position
    tensor_saveables, python_saveables))
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\tracking\util.py", line 289, in restore_saveables
    validated_saveables).restore(self.save_path_tensor)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\saving\functional_saver.py", line 255, in restore
    restore_ops.update(saver.restore(file_prefix))
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\saving\functional_saver.py", line 102, in restore
    restored_tensors, restored_shapes=None)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\saving\saveable_object_util.py", line 116, in restore
    self.handle_op, self._var_shape, restored_tensor)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py", line 297, in shape_safe_assign_variable_handle
    shape.assert_is_compatible_with(value_tensor.shape)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\framework\tensor_shape.py", line 1110, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
**ValueError: Shapes (1,) and (32,) are incompatible**

### Expected Behavior

Please let me know how you can solve the error.
 (E.g. there is a problem loading the model, etc.)

### Setup Details
Include the details about the versions of:
 - OS type and version: Windows 10 Professional
 - Python: 3.6.10
 - autokeras: 1.0.1
 - scikit-learn: 0.22.1
 - numpy: 1.18.1
 - keras: 1.0.8 (Keras-Applications)
 - scipy: 1.4.1
 - tensorflow: 2.1.0
 - pytorch: x

**Comment by ikscapes** [comment]
I reinstalled tensorflow and autokeras and ran it again.

Another error occurred while executing the code.

The full error log is shown below.
2020-02-12 20:43:47.329690: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at save_restore_v2_ops.cc:220 : Unknown: Failed to rename: .\auto_model\trial_d052e73d00eb40d2f1a00d4a472a874c\checkpoints\epoch_0\checkpoint_temp_43c9929389a54f28958954228a55ace5/part-00001-of-00002.data-00000-of-00001 to: .\auto_model\trial_d052e73d00eb40d2f1a00d4a472a874c\checkpoints\epoch_0\checkpoint.data-00001-of-00002 : �׼����� �źεǾ����ϴ�.
; Input/output error
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\ops\gen_io_ops.py", line 493, in merge_v2_checkpoints
    "delete_old_dirs", delete_old_dirs)
tensorflow.python.eager.core._FallbackException: This function does not handle the case of the path where all inputs are not already EagerTensors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Ikjoo/Tensorflow Projects/AutoML/autokeras_customized_model.py", line 38, in <module>
    auto_model.fit(x_train, y_train, epochs=300)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\autokeras\auto_model.py", line 250, in fit
    **kwargs)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\autokeras\engine\tuner.py", line 132, in search
    super().search(callbacks=new_callbacks, **fit_kwargs)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\kerastuner\engine\base_tuner.py", line 130, in search
    self.run_trial(trial, *fit_args, **fit_kwargs)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\autokeras\engine\tuner.py", line 91, in run_trial
    history = model.fit(x, *fit_args, **copied_fit_kwargs)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 397, in fit
    prefix='val_')
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 771, in on_epoch
    self.callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 302, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 992, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 1027, in _save_model
    self.model.save_weights(filepath, overwrite=True)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1123, in save_weights
    self._trackable_saver.save(filepath, session=session)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\tracking\util.py", line 1168, in save
    file_prefix=file_prefix_tensor, object_graph_tensor=object_graph_tensor)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\tracking\util.py", line 1116, in _save_cached_when_graph_building
    save_op = saver.save(file_prefix)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\training\saving\functional_saver.py", line 238, in save
    sharded_prefixes, file_prefix, delete_old_dirs=True)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\ops\gen_io_ops.py", line 499, in merge_v2_checkpoints
    delete_old_dirs=delete_old_dirs, name=name, ctx=_ctx)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\ops\gen_io_ops.py", line 525, in merge_v2_checkpoints_eager_fallback
    attrs=_attrs, ctx=ctx, name=name)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow_core\python\eager\execute.py", line 61, in quick_execute
    num_outputs)
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 288: invalid start byte**

There seems to be a problem with storing the model.
Could you tell me where to fix it?

**Comment by yoo817** [comment]
I have the same problem. Have you solved it yet?

**Comment by zhouzhou0109** [comment]
I have the same problem.
